## 16 语言词典(自动生成: tools/i18n_data_*.py -> 本文件)。
## key = 简体中文源文(必须与代码字面量逐字一致); 缺词回退英语(fallback)。
## zh_CN 为源语言, 由 I18n 注册恒等映射, 不在本表。
class_name StringsDb
extends RefCounted

const DB := {
	"en": {
		"⚔ 攻击": "⚔ Attack",
		"🛡 防御": "🛡 Defend",
		"✨ 技能": "✨ Skill",
		"✨技能": "✨Skill",
		"🔥火球": "🔥Fireball",
		"❄冰霜": "❄Frost",
		"✟圣光": "✟Holy",
		"冰霜": "Frost",
		"圣光": "Holy",
		"火球": "Fireball",
		"玩家": "Player",
		"(空位)": "(Empty)",
		"(你)": "(You)",
		"← 主菜单": "← Main Menu",
		"新手引导": "Tutorial",
		"昵称": "Nickname",
		"普通模式": "Classic Mode",
		"肉鸽模式": "Rogue Mode",
		"格斗试炼": "Fight Trials",
		"格斗": "Fight",
		"每日挑战": "Daily Challenge",
		"编成中…": "Drafting…",
		"跳过这组": "Skip This Pair",
		"返 回": "BACK",
		"防御": "Defend",
		"AI 难度": "AI Difficulty",
		"IP 或域名": "IP or domain",
		"▶ 当前回合": "▶ Current Turn",
		"⚔ 格斗试炼": "⚔ Fight Trials",
		"❄ 冻结": "❄ Frozen",
		"❄ 被冻结": "❄ Chilled",
		"⬇ 一键下载": "⬇ One-Click Download",
		"⬇ 发现新版本, 点击更新": "⬇ New version found — tap to update",
		"一回合": "1 round",
		"三回合": "3 rounds",
		"五回合": "5 rounds",
		"不占装备槽": "No equipment slot",
		"与服务器断开, 自动重连中…": "Disconnected from server, reconnecting…",
		"两位格斗者正在编成…": "Fighters are drafting…",
		"个 人 档 案": "P R O F I L E",
		"主机在线, 联机协商中… 若 15 秒后仍未进入, 请点【连接】重试": "Host online, negotiating… If not joined in 15s, tap [Connect] to retry",
		"今日未挑战": "Not attempted today",
		"保存并关闭": "Save & Close",
		"保存设置": "Save Settings",
		"全屏": "Fullscreen",
		"分辨率": "Resolution",
		"剪贴板中没有有效的邀请码(请先复制房主发的邀请信息)": "No valid invite code in clipboard (copy the host's invite first)",
		"加入": "Join",
		"化身头像人物, 五回合二选一编成 5 张装备, 决战 BOSS": "Pick 1 of 2 cards each round to build 5 equipment slots, then face the BOSS",
		"和朋友开一局: 联机游戏 → 创建房间 → 把房间码发给朋友": "Play with friends: Online → Create Room → share the room code",
		"商　城": "S H O P",
		"回合数": "Rounds",
		"回合胜 0": "Round Wins 0",
		"回合胜利!": "Round Won!",
		"回合落败": "Round Lost",
		"图像": "Graphics",
		"垂直同步": "V-Sync",
		"复制邀请码": "Copy Invite Code",
		"大富豪": "Tycoon",
		"奇物(特殊牌不占槽)": "Relics (specials take no slot)",
		"对局已结束 — 可等待房主开始下一局": "Match over — wait for the host to start the next one",
		"对方": "Opponent",
		"已复制: ": "Copied: ",
		"已编成": "Ready",
		"已编成 — 等待对手…": "Ready — waiting for opponent…",
		"已解锁": "Unlocked",
		"已连接! 选一个方式开局吧": "Connected! Pick a way to start",
		"已领取": "Claimed",
		"带王": "With Jokers",
		"应用分辨率": "Apply Resolution",
		"开始游戏": "Start",
		"成  就": "A C H I E V E",
		"成就·战绩": "Records",
		"或输入房间码": "or enter room code",
		"战  绩": "R E C O R D S",
		"房主": "Host",
		"房间": "Room",
		"技能": "Skill",
		"放弃试炼": "Abandon Run",
		"无法发起连接探测, 请检查网络": "Probe failed — check your network",
		"普通": "Normal",
		"服务器": "Server",
		"服务器版本更高, 请更新客户端": "Server is newer — please update the client",
		"未安装或未启动": "Not installed or not running",
		"未完成": "Not done",
		"未检测到局域网/Tailscale 地址": "No LAN/Tailscale address detected",
		"未解锁": "Locked",
		"未连接服务器(127.0.0.1 只是本机地址)。\n同一 WiFi: 点【本机开房】, 朋友在【搜索附近主机】一键加入;\n跨网联机: 安装并登录 Tailscale 后用邀请码开局。": "Not connected (127.0.0.1 is only this device).\nSame Wi-Fi: tap [Host Locally], friends join via [Find Nearby Hosts];\nAcross networks: install & log into Tailscale, then use an invite code.",
		"本地游戏": "Local Game",
		"本机服务器已启动": "Local server started",
		"格斗位": "Fighter Seat",
		"格斗对战": "Fight Duel",
		"格斗对战(2人)": "Fight Duel (2P)",
		"格斗者": "Fighter",
		"检测中…": "Checking…",
		"槽满: 立即生效": "Slots full: takes effect now",
		"模式": "Mode",
		"每局『命运二选一』定规则: 10 种命运卡随机登场": "Each match drafts 1 of 2 Fate Cards: 10 kinds appear at random",
		"每日 0 点重置 · 完成对局与任务可获金币钻石": "Resets daily at midnight · Play matches & missions for gold and diamonds",
		"每日任务": "Missions",
		"没有可移除的玩家(仅房主可移除非自己的人类玩家)": "No removable players (host can only remove other humans)",
		"点【复制邀请码】发给朋友 → 朋友点【粘贴邀请码, 一键加入】或【搜索附近主机】": "Tap [Copy Invite Code] to share → friends tap [Paste Invite Code] or [Nearby Hosts]",
		"留在房间": "Stay in Room",
		"离开": "Leave",
		"离开房间": "Leave Room",
		"离线·AI 代管": "Offline · AI managed",
		"移除玩家": "Remove Player",
		"空位加AI": "Add AI",
		"端口需为 1-65535 的数字": "Port must be 1-65535",
		"等待加入": "Waiting to join",
		"等待服务器…": "Waiting for server…",
		"签 到 领 取": "CLAIM",
		"签到": "Sign In",
		"简单": "Easy",
		"精英怪": "Elite",
		"终 局": "F I N A L",
		"终局": "Final",
		"经典大富豪: 换牌 / 革命 / 8切, 回合制排名结算": "Classic Daifugo: Swap / Revolution / 8-Cut, ranked scoring",
		"统  计": "S T A T S",
		"联机准备 · Tailscale": "Online Setup · Tailscale",
		"联机对战": "Online Duel",
		"联机游戏": "Online Game",
		"胜 利 !": "V I C T O R Y !",
		"装备 0/5 · 奇物 0": "Gear 0/5 · Relics 0",
		"装备槽": "Equipment",
		"装备槽已满 — 点上方要替换的槽位，或跳过": "Slots full — tap a slot above to replace, or skip",
		"装备槽已满 — 点击左上要替换的槽位，或跳过": "Slots full — tap a slot (top-left) to replace, or skip",
		"观战中": "Spectating",
		"观战位": "Spectator Seat",
		"规则设置": "Rules",
		"触感": "Haptics",
		"设  置": "S E T T I N G S",
		"设　置": "S E T T I N G S",
		"试炼结束": "Run over",
		"试炼通关!": "Trials cleared!",
		"请输入服务器地址": "Enter server address",
		"败 北…": "D E F E A T …",
		"输赢": "Stakes",
		"返回大厅": "Back to Lobby",
		"返回菜单": "Back to Menu",
		"还没有对局记录 — 去打一局吧!": "No match records yet — go play one!",
		"连接": "Connect",
		"退出游戏": "Quit Game",
		"选择游戏模式": "Select Game Mode",
		"选牌中…": "Picking…",
		"附近主机(同一 WiFi)": "Nearby Hosts (same Wi-Fi)",
		"集齐 5 张触发牌型协同": "Collect 5 cards to trigger combo synergies",
		"震动反馈(轮到你/结算)": "Vibration (your turn / results)",
		"革命": "Revolution",
		"音乐": "Music",
		"音效": "SFX",
		"音量": "Volume",
		"领 取": "CLAIM",
		"，本回合有额外候选组!": ", extra draft pair this round!",
		"，额外候选组!": ", extra draft pair!",
		"🂡 大富豪": "🂡 Tycoon",
		"🎲  快速匹配": "🎲 Quick Match",
		"🎲 肉鸽模式": "🎲 Rogue Mode",
		"🏠  创建房间": "🏠 Create Room",
		"🏠 本机开房(当主机)": "🏠 Host Locally",
		"👁 观战中 — 本房间仅 1/2 号位可出战": "👁 Spectating — only seats 1/2 fight in this room",
		"💥 重击(防御可减!)": "💥 Heavy (defend to reduce!)",
		"📅 每日挑战": "📅 Daily Challenge",
		"📋 粘贴邀请码, 一键加入": "📋 Paste Invite Code",
		"📕 命运卡图鉴": "📕 Fate Card Codex",
		"🔍 搜索附近主机": "🔍 Nearby Hosts",
		"🔥 法术(魔抗可减!)": "🔥 Spell (magic res. helps!)",
		"🟣 奇物生效! 补抽一张普通牌": "🟣 Relic active! Draft 1 extra normal card",
		"🥊 联机格斗对战": "🥊 Online Fight Duel",
		"同一 WiFi 的朋友: 联机页点【搜索附近主机】一键加入\n异地朋友: 点【复制邀请码】发给他(含全部地址)": "Same Wi-Fi friends: tap [Find Nearby Hosts] to join\nRemote friends: send them the [Copy Invite Code] (all addresses)",
		"Tailscale 已就绪 — 点【本机开房】创建房间, 把邀请码发给朋友;\n或点【粘贴邀请码, 一键加入】朋友的主机。": "Tailscale ready — tap [Host Locally] to create a room and share the code;\nor tap [Paste Invite Code] to join a friend.",
		"复活币生效!": "Revive coin used!",
		"第 %d/%d 回合 · 第 %d/%d 局    %s": "Round %d/%d · Hand %d/%d    %s",
		"? 联机帮助": "? Online Help",
		"关闭 ✕": "Close ✕",
		"◀ 上一页": "◀ Prev",
		"下一页 ▶": "Next ▶",
		"三步开始联机": "Get Online in 3 Steps",
		"朋友怎么连进来": "How Friends Join",
		"主机专用说明": "Host Guide",
		"常见问题": "FAQ",
		"① 本机开房(自动建房)": "1) Host Locally (auto room)",
		"② 复制邀请码 → 发给朋友": "2) Copy invite code → send to friends",
		"③ 朋友粘贴邀请码, 一键加入": "3) Friends paste the code — one tap to join",
		"朋友 A\n填 100.x.x.x → 连接": "Friend A\nenter 100.x.x.x → Connect",
		"朋友 B\n填 100.x.x.x → 连接": "Friend B\nenter 100.x.x.x → Connect",
		"主机(你) 100.y.y.y\n本机开房 · 房间码": "Host (you) 100.y.y.y\nlocal host · room code",
		"所有设备装 Tailscale": "All devices install Tailscale",
		"tailscale.com 免费下载": "tailscale.com — free download",
		"朋友在大厅右上角【服务器】里填 IP": "Friends enter the IP under [Server] (top-right)",
		"复制房间码": "Copy Room Code",
		"本机开房": "Host Locally",
		"创建房间": "Create Room",
		"房主专属: 开始游戏 / 空位加AI / 移除玩家 / 规则设置": "Host-only: Start / Add AI / Remove Player / Rules",
		"无法连接 → 看红字提示与目标地址": "Cannot connect → check the red hint and address",
		"已连接 → 三大按钮解锁": "Connected → main buttons unlock",
		"版本不符 → 弹出更新按钮": "Version mismatch → update prompt",
		"掉线 → 自动重连回座": "Disconnected → auto-rejoin",
		"连接失败会每 2 秒自动重试, 无需手动操作": "Failed connections retry every 2s automatically",
		"已找到主机 %s, 连接中, 连上后自动进房…": "Found host %s, connecting — will join automatically…",
		"未能确认主机可达, 仍尝试连接 %s:%d …": "Host not confirmed, still trying %s:%d…",
		"正在寻找主机…(%d/%d: %s)": "Searching for host… (%d/%d: %s)",
		"正在连接 %s:%d …": "Connecting to %s:%d…",
		"正在连接附近主机 %s:%d, 连上后自动进房 %s…": "Connecting to nearby host %s:%d, joining room %s…",
		"无法连接 %s:%d（第 %d 次），自动重试中…\n确认服务器已启动、地址正确、防火墙放行": "Cannot connect to %s:%d (attempt %d), retrying…\nCheck the server is running, the address is right, and the firewall allows it",
		"暂时无法到达 %s(仍在自动重试)—— 请确认:\n① 对方已点【本机开房】(服务器需在运行)\n② 同一 WiFi/局域网, 或双方 Tailscale 已连接\n③ 对方防火墙已放行 UDP %d": "Cannot reach %s (still retrying) — check:\n1) The host tapped [Host Locally] (server running)\n2) Same Wi-Fi/LAN, or both on Tailscale\n3) Their firewall allows UDP %d",
		"本地": "Local",
		"局域网  %s": "LAN  %s",
		"服务器 %s · ": "Server %s · ",
		" 等%d个地址": " +%d addresses",
		" , 发给朋友即可加入": ", send it to friends to join",
		"已被移出房间(%s)": "Removed from room (%s)",
		"已重新连上，座位已恢复": "Reconnected — seat restored",
		"对局已结束，返回房间": "Match ended, back to room",
		"连接断开，自动重连中…": "Disconnected — reconnecting…",
		"错误 %s: %s": "Error %s: %s",
		"房间  %s": "Room  %s",
		"座位 %d": "Seat %d",
		"(双倍卡)": "(x2 card)",
		" · 游戏中": " · playing",
		"✓ 已就绪  %s": "✓ Ready  %s",
		"⬇ 一键下载\n(%s)": "⬇ One-tap install\n(%s)",
		"⬇ 异地联机装 Tailscale\n(%s)": "⬇ Install Tailscale\n(%s)",
		"花色与属性": "Suits & Stats",
		"你的扑克就是你的装备, 数值越大属性越强:": "Your playing cards are your gear — bigger numbers, stronger stats:",
		"牌型协同": "Combo Synergy",
		"每张牌都有小幅单卡加成(♠物攻+4·暴击+5% / ♥生命 / ♦防抗 / ♣技能, 点数越高越多);\n组合自动触发套装加成(越大越强), 不满 5 张也可判型:": "Each card gives a small individual bonus (♠ atk+4·crit+5% / ♥ HP / ♦ armor / ♣ skill, more with higher ranks);\ncombos trigger set bonuses (better hand, stronger) — fewer than 5 cards still count:",
		"五张变身": "5-Card Transform",
		"集满 5 张装备牌即触发『变身』: 光环随主花色变色,\n全属性 +5%, 冲刺距离更远, 下一层重置后重新集满再次变身:": "Fill all 5 slots to Transform: your aura takes your dominant suit's color,\nall stats +5%, longer dash. Slots reset each floor — fill again to transform anew:",
		"回合流程": "Round Flow",
		"共 5 回合: 每回合先『二选一』抽 1 张牌, 再战斗:": "5 rounds: each starts with a pick-one draft, then battle:",
		"战斗操作": "Battle Actions",
		"回合制三选操作; 怪物意图公示, 见招拆招:": "Turn-based, pick one of three; the monster telegraphs its intent — counter it:",
		"连击与奥义": "Combo & Ultimate",
		"连击加成 + 怒气大招 + 完美格挡, 三重爽点:": "Combo bonus + fury ultimate + perfect guard — triple satisfaction:",
		"稀有卡与无尽": "Rare Cards & Endless",
		"金框稀有卡 + 通关后无尽挑战:": "Gold-framed rare cards + Endless mode after clearing:",
		"二选一抽 1 张 → 打小怪": "Pick 1 of 2 → fight a mob",
		"再抽 1 张(共 2 张装备) → 打小怪": "Draft again (2 equipped) → mob",
		"再抽 1 张(共 3 张) → 精英怪!": "Draft again (3 equipped) → elite!",
		"再抽 1 张(共 4 张) → 打小怪": "Draft again (4 equipped) → mob",
		"集齐 5 张装备 → 决战 BOSS!": "All 5 equipped → BOSS showdown!",
		"黑桃 · 物攻": "♠ Spades — Attack",
		"红桃 · 生命": "♥ Hearts — HP",
		"方块 · 护甲/魔抗": "♦ Diamonds — Armor/MRes",
		"梅花 · 法术": "♣ Clubs — Skill",
		"数值合计 = 物理攻击; 张数越多暴击率/爆伤越高": "Value sum = physical attack; more ♠ = higher crit rate & crit damage",
		"数值合计 = 生命上限加成, 越多越肉": "Value sum = max HP bonus; more ♥ = tankier",
		"数值合计 = 护甲/魔抗": "Value sum = armor & magic resistance",
		"数值合计 = 技能强度; 张数决定技能流派": "Value sum = skill power; ♣ count picks your school",
		"♠ 赤红战魂": "♠ Crimson Soul",
		"♥ 翠绿生机": "♥ Verdant Spirit",
		"♦ 金刚护体": "♦ Adamant Guard",
		"♣ 苍蓝法魂": "♣ Azure Arcane",
		"变身: 全属性 +5% · 冲刺更远 · 下一层重新集满再变身": "Transform: all stats +5% · longer dash · fill 5 slots again next floor",
		"第 1 回合": "Round 1",
		"第 2 回合": "Round 2",
		"第 3 回合": "Round 3",
		"第 4 回合": "Round 4",
		"第 5 回合": "Round 5",
		"物理伤害, 可暴击(♠ 越多越频繁/越痛)": "Physical damage, can crit (more ♠ = more & bigger crits)",
		"♣ 法术伤害, 冷却 2 回合; ♣ 张数定流派: 火球/冰霜/圣光": "♣ Magic damage, 2-turn cooldown; ♣ count picks the school: Fire/Frost/Holy",
		"本回合减伤 60% 并回血 — 盯紧怪物意图再决定!": "60% less damage this turn plus healing — watch the monster's intent!",
		"怪物头顶公示下一手: ⚔攻击 / 💥重击 / 🔥法术 / ⚡蓄力必杀": "The monster telegraphs its next move: ⚔attack / 💥heavy / 🔥spell / ⚡charge special",
		"连击 5 层下击必暴 / 8 层怒气 +30": "Combo 5: next hit crits / 8: fury +30",
		"预读重击时防御 → 零伤害 + 全额反击 + 怒气 25!": "Guard on a telegraphed heavy → zero damage + full counter + fury 25!",
		"攻/受/击破积攒; 满 100 释放奥义: 2.5 倍攻击 + 回血 20%": "Builds from hits dealt/taken/kills; at 100: ultimate 2.5× attack + 20% heal",
		"每回合按受伤量评 S/A/B; S 级奖励额外怒气": "Each round grades S/A/B by damage taken; S grants bonus fury",
		"候选 12% 出现, 装备后生命上限永久 +8% + 奖励怒气": "12% draft chance; equip for permanent +8% max HP + bonus fury",
		"无尽模式": "Endless Mode",
		"R5 通关后可继续挑战, 怪物每轮 ×1.35 变强": "Keep playing past round 5 — monsters grow ×1.35 each round",
		"打出含 8 的牌 / 清空桌面续领": "Play any 8 / clear the table to keep the buff",
		"BOSS 击破! 可继续下一层!": "BOSS down! Next floor unlocked!",
		"BOSS 必杀": "BOSS Special",
		"BOSS 蓄力后释放组别专属技能: 缠绕吸血/暗影尖啸/烈焰灼烧/极寒冰冻/亡者回复": "Charged BOSSes unleash signature skills: Entangle / Shadow Shriek / Flame Breath / Deep Freeze / Undead Rally",
		"连击里程碑": "Combo Milestone",
		"必杀造成伤害": "The special deals damage",
		"金框稀有卡": "Gold-framed rare card",
		"集满五张变身": "5 cards — Transform!",
		"连击上限 16, 连击伤害加成提升至 6%/层": "Combo cap 16, combo bonus raised to 6% per stack",
		"技能冷却缩短为 1 回合": "Skill cooldown reduced to 1 turn",
		"狂暴之眼": "Eye of Frenzy",
		"时之沙漏": "Hourglass",
		"玉障": "Jade Barrier",
		"泉涌珠": "Spring Pearl",
		"先制符": "First-Strike Charm",
		"荆棘甲": "Thorn Mail",
		"嗜血牙": "Vampiric Fang",
		"狂化面具": "Berserk Mask",
		"增援令": "Reinforcement Order",
		"锁环": "Lock Ring",
		"肉鸽模式 · 玩法": "Rogue Mode — How It Plays",
		"规则主体与普通模式[color=#e0a83c]完全一致[/color](换牌/革命/8切/回合制排名)。\n区别只有一条: [color=#7dd87d]每局开始随机抽一张『命运卡』[/color], 本局内生效。\n命运卡来自固定图鉴(共 [color=#ffd166]11 种[/color], 见后几页), 抽到哪张全凭运气——随机性与可玩性由此而来。\n每张命运卡还有 [color=#b070e0]稀有度[/color]: 普通(白) < 史诗(紫) < 传说(金), 越稀有越强!": "The core rules are [color=#e0a83c]identical[/color] to Classic (card swap/Revolution/8-cut/ranked rounds).\nOne difference: [color=#7dd87d]each match draws a random Fate Card[/color], active for the whole match.\nFate Cards come from a fixed codex ([color=#ffd166]11 total[/color], see next pages) — which one you draw is pure luck: that is where the fun lives.\nEach card also has [color=#b070e0]rarity[/color]: Common(white) < Epic(purple) < Legendary(gold) — rarer is stronger!",
		"命运卡图鉴 · 发牌与规则": "Fate Codex — Dealing & Rules",
		"发牌类与规则类命运卡:": "Dealing-type and Rules-type Fate Cards:",
		"命运卡图鉴 · 触发与结算": "Fate Codex — Triggers & Payout",
		"触发类与结算类命运卡:": "Trigger-type and Payout-type Fate Cards:",
		"命运卡图鉴 · 我的进度": "Fate Codex — My Progress",
		"本机记录每张命运卡的出现与选用次数:": "This device tracks how often each Fate Card appeared and was picked:",
		"普通模式 · 目标与身份": "Classic Mode — Goal & Ranks",
		"目标只有一个: [color=#7dd87d]尽快出完手牌[/color]!\n出完的先后决定身份 —— [color=#e0a83c]大富豪 → 富豪 → 贫民 → 大贫民[/color],\n身份带来不同积分, 多回合累积后统一结算。": "One goal: [color=#7dd87d]empty your hand first[/color]!\nFinishing order decides your rank — [color=#e0a83c]Tycoon → Millionaire → Pauper → Beggar[/color],\neach rank earns different points, tallied after all rounds.",
		"普通模式 · 核心规则": "Classic Mode — Core Rules",
		"三条改变牌局走向的核心规则:": "Three rules that swing the game:",
		"普通模式 · 回合与结算": "Classic Mode — Rounds & Payout",
		"回合制对战, 多局累积定胜负:": "Round-based play; multiple hands decide the winner:",
		"出完先后定身份, 积分多回合累积": "Finishing order sets ranks; points accumulate across hands",
		"出完的先后决定身份 —— [color=#e0a83c]大富豪 → 富豪 → 贫民 → 大贫民[/color],": "Finishing order decides ranks — [color=#e0a83c]Tycoon → Millionaire → Pauper → Beggar[/color],",
		"身份带来不同积分, 多回合累积后统一结算。": "Ranks earn different points, tallied after all hands.",
		"每局按身份计分, 全部回合结束后统一结算\n胜者多拿钻石 —— 大富豪 +2 / 富豪 +1": "Points by rank each hand, tallied at the end\nWinners earn extra diamonds — Tycoon +2 / Millionaire +1",
		"大贫民→大富豪 2 张 / 贫民→富豪 1 张": "Beggar→Tycoon 2 cards / Pauper→Millionaire 1",
		"命运卡: 正负反转": "Fate Card: Polarity Flip",
		"命运卡: 结算×2": "Fate Card: Payout ×2",
		"抽命运卡": "Draw Fate Card",
		"选定的命运卡在本层生效": "The chosen Fate Card is active this floor",
		"每局必定抽一张; 11 种命运卡见后几页": "One card every match; 11 Fate Cards on the next pages",
		"命运二选一": "Fate: Pick One of Two",
		"命运二选一 · 第 %d 层": "Fate Draft · Floor %d",
		"命运卡 · 第 %d 局 · %s类效果": "Fate Card · Match %d · %s",
		"命运卡来自固定图鉴(共 [color=#ffd166]11 种[/color], 见后几页), 抽到哪张全凭运气——随机性与可玩性由此而来。\n每张命运卡还有 [color=#b070e0]稀有度[/color]: 普通(白) < 史诗(紫) < 传说(金), 越稀有越强!": "Fate Cards come from a fixed codex ([color=#ffd166]11 total[/color], see next pages) — which one you draw is pure luck: that is where the fun lives.\nEach card also has [color=#b070e0]rarity[/color]: Common(white) < Epic(purple) < Legendary(gold) — rarer is stronger!",
		"区别只有一条: [color=#7dd87d]每局开始随机抽一张『命运卡』[/color], 本局内生效。": "One difference: [color=#7dd87d]each match draws a random Fate Card[/color], active for the whole match.",
		"规则主体与普通模式[color=#e0a83c]完全一致[/color](换牌/革命/8切/回合制排名)。": "The core rules are [color=#e0a83c]identical[/color] to Classic (card swap/Revolution/8-cut/ranked rounds).",
		"触发类在对局中实时播报; 结算奖励与普通模式完全一致": "Trigger cards announce in real time; payouts are identical to Classic",
		"发牌类改牌堆构成; 规则类改当局长打法": "Dealing cards change the deck; rule cards change how the match plays",
		"收集进度 %d/%d — 见齐全部命运卡解锁隐藏成就": "Collection %d/%d — see every Fate Card to unlock a hidden achievement",
		"%s%s %s — 出现 %d · 选用 %d": "%s%s %s — seen %d · picked %d",
		"肉鸽": "Rogue",
		"[color=#7dd87d]同一 WiFi[/color]: 房主点 [color=#e0a83c]【本机开房】[/color], 朋友点 [color=#e0a83c]【搜索附近主机】[/color]\n直接点击房间加入——最简单, 无需安装任何东西。\n[color=#7dd87d]异地联机[/color](准备一次性): 每台设备安装并登录 [color=#e0a83c]Tailscale[/color](免费),\n本页左侧【联机准备】自动检测, 未安装可一键下载。\n然后: ①房主【本机开房】 ②【复制邀请码】发给朋友 ③朋友【粘贴邀请码, 一键加入】。": "[color=#7dd87d]Same Wi-Fi[/color]: host taps [color=#e0a83c][Host Locally][/color], friends tap [color=#e0a83c][Find Nearby Hosts][/color]\nthen tap the room to join — simplest, nothing to install.\n[color=#7dd87d]Across networks[/color] (one-time setup): every device installs & logs into [color=#e0a83c]Tailscale[/color] (free),\nauto-detected under [Online Prep] on the left — one tap to install if missing.\nThen: 1) host [Host Locally] 2) [Copy Invite Code] → friends 3) friends [Paste Invite Code] to join.",
		"[color=#7dd87d]方式一 · 同一 WiFi(最简单)[/color]: 双方连同一个 WiFi,\n房主【本机开房】后, 朋友在联机页点 [color=#e0a83c]【搜索附近主机】[/color],\n看到房间直接点击即加入——无需任何账号和安装。\n[color=#7dd87d]方式二 · 异地联机[/color]: 所有设备安装 [color=#e0a83c]Tailscale[/color](免费)并用【同一个账号】登录,\n朋友点【粘贴邀请码, 一键加入】即可, 跨城市/跨运营商都没有问题。": "[color=#7dd87d]Way 1 · Same Wi-Fi (easiest)[/color]: both on the same Wi-Fi,\nafter the host taps [Host Locally], friends tap [color=#e0a83c][Find Nearby Hosts][/color]\nand tap the room to join — no accounts, no installs.\n[color=#7dd87d]Way 2 · Across networks[/color]: all devices install [color=#e0a83c]Tailscale[/color] (free) and log into the [color=#e0a83c]same account[/color],\nfriends tap [Paste Invite Code] to join — works across cities and carriers.",
		"[color=#e0a83c]搜索不到附近主机?[/color] 确认双方连同一个 WiFi、路由器未开「AP 隔离」;\n也可在【服务器】手动填主机信息卡的局域网 IP 后点【连接】。\n[color=#e0a83c]一直「无法连接」?[/color] 确认主机在线、双方 Tailscale 都已登录(异地时)。\n[color=#e0a83c]被踢出并提示版本?[/color] 主机的游戏版本更新了, 重新下载进入即可。\n[color=#e0a83c]对局中掉线?[/color] 自动凭凭证重连回座(掉线期间 AI 代打), 无需任何操作。": "[color=#e0a83c]Can't find nearby hosts?[/color] Both on the same Wi-Fi and AP isolation off;\nor type the host's LAN IP under [Server] and tap [Connect].\n[color=#e0a83c]Still cannot connect?[/color] Host online, both Tailscale logged in (for remote).\n[color=#e0a83c]Kicked with a version notice?[/color] The host's game updated — download and rejoin.\n[color=#e0a83c]Dropped mid-match?[/color] You rejoin automatically (AI plays while away).",
		"【本机开房】会在后台启动一台内置服务器, 你的客户端自动连入本机。\n点完后信息卡会列出你的全部地址: [color=#e0a83c]局域网 192.168.x.x[/color](同 WiFi 朋友用)\n和 [color=#e0a83c]Tailscale 100.x.x.x[/color](异地朋友用), 邀请码自动包含全部地址。\n服务器地址会被记住; 朋友连你, 改的是[color=#e0a83c]朋友自己[/color]的【服务器】地址。\n房主权限: 空位加AI / 开始游戏 / 移除玩家 / 修改规则(开局前)。": "[Host Locally] starts a built-in server in the background and joins your client to it.\nThe info card lists all your addresses: [color=#e0a83c]LAN 192.168.x.x[/color] (same Wi-Fi)\nand [color=#e0a83c]Tailscale 100.x.x.x[/color] (remote); the invite code includes them all.\nYour server address is remembered; friends change [color=#e0a83c]their own[/color] [Server] address.\nHost powers: Add AI / Start / Remove Player / Rules (before starting).",
		" ? 联机帮助": "? Online Help",
		"富豪": "Millionaire",
		"贫民": "Pauper",
		"大贫民": "Beggar",
		"排名": "Rank",
		"积分": "Points",
		"牌": "cards",
		"手": "moves",
		"对局回放(点击观看)": "Replays (tap to watch)",
		"对局回放": "Replays",
		"回放": "Replay",
		"%s · %s · %d 手": "%s · %s · %d moves",
		"▶ %s · %s · %d 手": "▶ %s · %s · %d moves",
		"战绩已清空!": "Records cleared!",
		"确认清空?": "Sure?",
		"清 空": "CLEAR",
		"一键清零": "Reset all",
		"导入失败: %s": "Import failed: %s",
		"导入成功: 金币 %d · 钻石 %d": "Imported: gold %d · diamonds %d",
		"导出备份码": "Export Backup Code",
		"导出备份码复制给新设备, 导入后恢复全部进度(金币/钻石/装扮/成就)": "Export a code for your new device — importing restores everything (gold/diamonds/cosmetics/achievements)",
		"备份码已复制到剪贴板, 发给新设备粘贴导入": "Backup code copied — paste it on your new device",
		"备份": "Backup",
		"粘贴备份码": "Paste backup code",
		"导 入": "IMPORT",
		"查看 %s 玩法说明": "%s — how to play",
		"查看成就与战绩": "View achievements & records",
		"每日签到 · 连续 %d 天": "Daily Sign-in · %d-day streak",
		"签到成功: %+d金币 %+d钻石": "Signed in: +%d gold +%d diamonds",
		"任务奖励: %+d金币 %+d钻石": "Mission reward: +%d gold +%d diamonds",
		"第%d天\n%s": "Day %d\n%s",
		"第%d天 / %s": "Day %d / %s",
		"💎": "💎",
		"🪙": "🪙",
		"双倍钻石卡": "Double Diamonds",
		"三倍钻石卡": "Triple Diamonds",
		"复活币": "Revive Coin",
		"命运骰": "Fate Dice",
		"重抽券": "Redraft Ticket",
		"清空战绩": "Clear Records",
		"激活后至当日结束, 对局获得的钻石 ×2": "Diamonds earned ×2 for the rest of today",
		"激活后至当日结束, 对局获得的钻石 ×3 (覆盖双倍卡)": "Diamonds earned ×3 for the rest of today (overrides ×2)",
		"格斗试炼倒下时自动消耗 1 枚, 以 60% 生命原地复活": "Auto-consumed when you fall in Fight Trials — revive on the spot at 60% HP",
		"肉鸽命运二选一界面可掷骰重抽候选(每次消耗 1 枚)": "Reroll the Fate draft options (consumes 1 per use)",
		"格斗选牌界面额外重抽次数 +1 (每次消耗 1 张)": "+1 redraft in the Fight draft (consumes 1 per use)",
		"购买成功, 已生效!": "Purchased and activated!",
		"购买成功, 已装备!": "Purchased and equipped!",
		"余额不足, 先去赚一赚吧": "Not enough balance — go earn some!",
		"钻石不足, 打几局赚钻石吧": "Not enough diamonds — play a few matches",
		"购买失败": "Purchase failed",
		"持有 %d": "Owned ×%d",
		"已拥有": "Owned",
		"装 备": "EQUIP",
		"使用中": "In use",
		"购 买": "BUY",
		"人 物 皮 肤": "CHARACTERS",
		"卡 牌 面 貌": "CARD DECKS",
		"特 殊 道 具": "SPECIAL ITEMS",
		"商  城": "SHOP",
		"生效中·今日": "Active today",
		"对局钻石 ": "Match diamonds ",
		"倒下时 ": "When you fall ",
		"命运二选一 ": "Fate: pick one of two ",
		"选牌重抽 ": "Draft redraft ",
		"战绩记录 ": "Battle records ",
		"立即清空全部对局记录、胜负统计与各模式战绩(不可逆)": "Instantly wipes all match records, win/loss stats and mode records (irreversible)",
		"属性一览": "Stats",
		"局数 %d · 通关 %d · 最远第 %d 回合 · 击破 BOSS %d": "Runs %d · Clears %d · Best round %d · Bosses %d",
		"胜场 %d": "Wins %d",
		"累计参与 %d 天": "Joined %d days",
		"今日已通关(剩余生命 %d%%)": "Cleared today (%d%% HP left)",
		"今日最佳: 到达第 %d 回合": "Today's best: round %d",
		"命运卡图鉴": "Fate Codex",
		"已见 %d / %d 种": "Seen %d / %d",
		"每日挑战通关!": "Daily cleared!",
		"每日挑战结束": "Daily over",
		"通过 %d/5 回合 · 历史最佳第 %d 层\n奖励: %d 钻石 已入账": "Cleared %d/5 rounds · Best %d\nReward: %d diamonds added",
		"通过 %d/5 回合 · 历史最佳第 %d 层\n失败惩罚: %d 金币 · 未获得钻石": "Cleared %d/5 rounds · best floor %d\nLoss penalty: %d gold · no diamonds",
		"返回后本局由 AI 托管继续, 从首页可回到本局。": "After leaving, AI plays on — you can return from the main menu.",
		"返回菜单？": "Back to menu?",
		"离开对局": "Leave Match",
		"离开对局？": "Leave match?",
		"离开后你的座位由 AI 代管(弃局), 并返回大厅。": "Your seat goes to AI (forfeit) and you return to the lobby.",
		"必杀": "SPECIAL",
		"🔥 灼烧 %d 回合": "🔥 Burn for %d turns",
		"🔥 灼烧 -%d": "🔥 Burn -%d",
		"❄ 被冰冻!": "❄ Frozen!",
		"⚡ 蓄力: %s(此回合承伤+50%!)": "⚡ Charging: %s (takes +50% damage this turn!)",
		"⚡ 蓄力中…": "⚡ Charging…",
		"⚡ 怒气": "⚡ Fury",
		"技能 -%d": "Skill -%d",
		"冷却 %d": "CD %d",
		"怒气满 100 释放": "Unleash at 100 fury",
		"完美格挡": "Perfect Guard",
		"完美格挡! 反击 -%d": "Perfect parry! Counter -%d",
		"变 身!": "TRANSFORM!",
		"必杀技": "Special",
		"%s 释放必杀技「%s」!": "%s unleashes [%s]!",
		"失败惩罚: %d 金币 · 未获得钻石": "Loss penalty: %d gold · no diamonds",
		"奖励: %d 钻石 已入账": "Reward: %d diamonds banked",
		"称号 %s · %d胜/%d场": "Title %s · %dW/%dM",
		"%s · %d胜/%d场": "%s · %dW/%dM",
		"战绩": "Records",
		"成 就": "Awards",
		"战 绩": "Records",
		"统 计": "Stats",
		"奖励": "Rewards",
		"奖励: %s · 进度 %d/%d": "Reward: %s · progress %d/%d",
		"赢得一场胜利": "Win a match",
		"完成 2 场对局": "Play 2 matches",
		"打出一次四条(炸弹)": "Play a four-of-a-kind",
		"格斗试炼通过 1 层": "Clear a Fight Trials floor",
		"领取": "CLAIM",
		"出现": "seen",
		"选用": "picked",
		"出现/选用": "seen/picked",
		"初阵告捷": "First Victory",
		"渐入佳境": "Warming Up",
		"牌桌老手": "Table Veteran",
		"所向披靡": "Undefeated",
		"常客": "Regular",
		"小有积蓄": "Nest Egg",
		"腰缠万贯": "Deep Pockets",
		"收藏家": "Collector",
		"大买家": "Big Spender",
		"风雨无阻": "Rain or Shine",
		"向死而生": "Back from the Dead",
		"试炼制霸": "Trial Champion",
		"试炼大师": "Trial Master",
		"每日战士": "Daily Warrior",
		"持之以恒": "Persistence",
		"命运之子": "Child of Fate",
		"命运主宰": "Fate Master",
		"命运收藏家": "Fate Collector",
		"擂台新人": "Arena Rookie",
		"赢得第一场胜利": "Win your first match",
		"累计获胜 10 场": "Win 10 matches",
		"累计获胜 30 场": "Win 30 matches",
		"累计获胜 50 场": "Win 50 matches",
		"完成 30 场对局": "Play 30 matches",
		"累计获得 50 颗钻石": "Earn 50 diamonds in total",
		"金币持有量达到 1000": "Hold 1,000 gold",
		"拥有 8 件装扮(皮肤+卡面)": "Own 8 cosmetics (skins + decks)",
		"购入一张双倍钻石卡": "Buy a Double Diamonds card",
		"连续签到满 7 天": "Sign in 7 days in a row",
		"完成一次格斗试炼": "Finish a Fight Trial",
		"格斗试炼打进第 5 回合(BOSS 战)": "Reach round 5 of Fight Trials (BOSS)",
		"通关格斗试炼 3 次": "Clear Fight Trials 3 times",
		"商城累计消费 5 次": "Make 5 shop purchases",
		"使用复活币重返战场": "Return to battle with a Revive Coin",
		"通关格斗试炼(击败 BOSS)": "Clear Fight Trials (beat the BOSS)",
		"通关格斗试炼 5 次": "Clear Fight Trials 5 times",
		"完成一次每日挑战": "Complete a Daily Challenge",
		"累计 3 天参与每日挑战": "Play Daily Challenge on 3 days",
		"肉鸽模式取得 1 场胜利": "Win a Rogue match",
		"肉鸽模式取得 10 场胜利": "Win 10 Rogue matches",
		"图鉴见齐全部 10 张命运卡": "See all 10 Fate Cards",
		"联机格斗对战取得 1 场胜利": "Win an online Fight Duel",
		"🏆 成就解锁: %s": "🏆 Achievement: %s",
		"翡翠森林": "Jade Forest",
		"回声洞穴": "Echo Caverns",
		"熔火之心": "Molten Core",
		"冰封雪原": "Frozen Tundra",
		"幽暗墓地": "Gloomy Graveyard",
		"毒蘑菇": "Poison Shroom",
		"巨毒蘑菇": "Toxic Shroom",
		"古树妖": "Elder Treant",
		"森林巨鹿": "Forest Stag Lord",
		"洞穴蝙蝠": "Cave Bat",
		"血翼蝠王": "Bloodwing Bat King",
		"岩石傀儡": "Rock Golem",
		"深渊魔王": "Abyss Demon Lord",
		"熔岩史莱姆": "Lava Slime",
		"熔岩大史莱姆": "Lava Mega Slime",
		"炎魔卫士": "Flame Guard",
		"熔岩龙王": "Molten Dragon King",
		"雪原狼": "Tundra Wolf",
		"霜牙雪狼": "Frostfang Wolf",
		"冰晶卫士": "Ice Crystal Guard",
		"极寒霜龙": "Permafrost Dragon",
		"骷髅兵": "Skeleton Soldier",
		"腐骸骷髅": "Rotting Skeleton",
		"死灵法师": "Necromancer",
		"亡灵君王": "Undead King",
		"地下城": "Dungeon",
		"王者归来": "Return of the King",
		"天生革命": "Born Revolution",
		"疾风迅雷": "Blitz",
		"缩地成寸": "Shrinking Hands",
		"混沌换牌": "Chaos Swap",
		"龙王之怒": "Dragon King's Wrath",
		"双倍赌局": "Double Stakes",
		"无王之地": "Land Without Jokers",
		"免战之约": "No-Swap Pact",
		"福祸反转": "Fortune Flip",
		"八喜临门": "Lucky Eights",
		"狂暴": "Enraged!",
		"—— 自由出牌 ——": "— Free lead —",
		"首手必须包含 ♦3": "First play must include ♦3",
		"首局首出必须包含 ♦3": "The first lead of the first hand must include ♦3",
		"领出时不能不要": "You cannot pass when leading",
		"压不过上一手": "Cannot beat the last play",
		"没有这张牌": "You don't have that card",
		"牌型不合法": "Invalid combination",
		"操作无效 (%s)": "Invalid action (%s)",
		"还没轮到你": "Not your turn yet",
		"轮到你出牌": "Your turn — play a card",
		"需选择 %d 张返还": "Pick %d cards to return",
		"需选择 %d 张返还给 %s（已选 %d%s）": "Pick %d cards to return to %s (chosen %d%s)",
		"确认返还": "Confirm Return",
		"换牌：请选 %d 张返还给 %s（已选 %d%s）": "Swap: pick %d cards to return to %s (chosen %d%s)",
		"第 %d 层 · 第 %d/%d 回合 · %s": "Floor %d · Round %d/%d · %s",
		"第 %d/%d 回合 — 二选一编成": "Round %d/%d — draft your gear",
		"第 %d 层开始 — %s 地下城": "Floor %d begins — %s Dungeon",
		"第 1 层 — %s 地下城": "Floor 1 — %s Dungeon",
		"第 %d 回合 %s: %s 出现! HP %d / 攻击 %d": "Round %d %s: %s appears! HP %d / ATK %d",
		"上轮  ": "Last trick:  ",
		"8切": "8-Cut",
		"革命!": "REVOLUTION!",
		"记牌": "Counter",
		"提示": "Hint",
		"出牌": "PLAY",
		"统一结算": "Final Payout",
		"本局结束   ": "Hand over   ",
		"全场结束！  ": "Match over!  ",
		"结算: 积分 %+d × %d  =  ": "Payout: points %+d × %d  =  ",
		"%s  %s  %+d 分（总 %d）": "%s  %s  %+d pts (total %d)",
		"不要": "PASS",
		"发送": "SEND",
		"表情": "Emotes",
		"快捷回复": "Quick Chat",
		"表情发太快了": "Emotes flying too fast",
		"说太快了": "Chatting too fast",
		"说点什么…": "Say something…",
		"轮到你出牌 (需同牌型更大)": "Your turn (need a bigger same-type hand)",
		"（需同牌型更大）": "(must beat the same type)",
		"（%d 局）": "(%d hands)",
		"中 ×2": "Mid ×2",
		"小 ×1": "Small ×1",
		"大 ×3": "Big ×3",
		"设置": "Settings",
		"规则": "Rules",
		"评级": "Grade",
		"连击": "Combo",
		"里程碑": "Milestone",
		"怒气": "Fury",
		"—": "—",
		"大家好": "Hello everyone",
		"大家好，多多关照": "Hello, nice to meet you all",
		"大家好，很高兴见到各位": "Hi all — great to see you",
		"快点吧": "Hurry up",
		"快点吧，我等到花儿都谢了": "Hurry up — I've been waiting forever",
		"别走": "Don't go",
		"稳住": "Steady",
		"稳住，我们能赢": "Steady — we can win this",
		"打得好": "Well played",
		"你的牌打得太好了": "Your cards are amazing",
		"唉，手气太差了": "Ugh, terrible luck",
		"手气差": "Bad luck",
		"关照": "Go easy on me",
		"底牌多": "Holding many cards",
		"底牌留太多了吧": "You kept too many cards",
		"不要走，决战到天亮": "Stay — let's play till dawn",
		"等待 %s 出牌…": "Waiting for %s to play…",
		"等待 %s 选牌返还…": "Waiting for %s to return cards…",
		"开始对局": "Start Match",
		"再来一场": "Play Again",
		"下一局 · 再抽": "Next match · redraft",
		"局间交换": "Inter-hand Swap",
		"强制换牌": "Forced Swap",
		"结算(积分×命运卡)": "Payout (points × Fate)",
		"一对": "Pair",
		"三条": "Trips",
		"两对": "Two Pair",
		"四条": "Four of a Kind",
		"同花": "Flush",
		"同花顺": "Straight Flush",
		"葫芦": "Full House",
		"高牌": "High Card",
		"上家": "Left",
		"下家": "Right",
		"对家": "Across",
		"你": "You",
		"大": "T",
		"富": "M",
		"豪": "Y",
		"先选牌": "Draft first",
		"意图公示": "Intent",
		"首胜+%d": "first win +%d",
		"%d金币": "%d gold",
		"%d钻石": "%d diamonds",
		"全属性 +25%": "All stats +25%",
		"全属性+30% · 吸血 25%": "All stats +30% · vamp 25%",
		"全属性+90%": "All stats +90%",
		"主属性 ×2(花色决定方向)": "Main stat ×2 (suit decides)",
		"护甲/魔抗 ×1.6": "Armor/MRes ×1.6",
		"物攻 ×1.55": "Attack ×1.55",
		"物攻 ×2.0": "Attack ×2.0",
		"无加成": "No bonus",
		"冰冻玩家, 下次攻击伤害减半": "Freezes you — your next attack deals half damage",
		"亡者召唤": "Undead Rally",
		"重击并吸取生命": "Heavy hit and drains life",
		"重击并回复自身生命": "Heavy hit and heals itself",
		"重击并施加灼烧": "Heavy hit and applies burn",
		"无视护甲魔抗的重击": "Heavy hit that ignores armor and magic resistance",
		"四条即革命\n大小顺序颠倒": "Four of a kind = Revolution\nrank order flips",
		"四条即革命 / 大小顺序颠倒": "Four of a kind = Revolution\nrank order flips",
		"每 3 回合追加一次连击": "Bonus attack every 3 turns",
		"每场战斗开始获得 20% 生命护盾": "Start each battle with a 20% HP shield",
		"每场战斗的首次攻击必定暴击": "Your first attack each battle always crits",
		"每回合开始回复 5% 生命": "Heal 5% HP at the start of every turn",
		"反弹所受物理伤害的 30%": "Reflects 30% of physical damage taken",
		"攻击与技能附带 20% 吸血": "Attacks and skills lifesteal 20%",
		"下回合起每回合额外多一组二选一": "From next round, an extra pick-one pair every round",
		"持有期间每轮未选中的候选牌下回合保留": "Unpicked draft candidates are kept for the next round",
		"技能+4 · 点数+%d": "Skill +4 · rank +%d",
		"护甲/魔抗+3 · 点数+%d": "Armor/MRes +3 · rank +%d",
		"物攻+4 · 暴击率+5%% · 点数+%d": "Attack +4 · crit +5%% · rank +%d",
		"生命+5+3×点数(+%d) ": "HP +5+3×rank (+%d) ",
		"王×%d": "Joker ×%d",
		"，剩余 %d 秒": ", %d seconds left",
		"★★": "★★",
		"◆ 史诗": "◆ Epic",
		"★ 传说": "★ Legendary",
		"⚡ 蓄力": "⚡ Charging",
		"【奇物】%s": "[Relic] %s",
		"🎲 掷命运骰重抽 (持有 %d)": "🎲 Fate Dice reroll (owned %d)",
		"🏠 %s  %d/%d人  %s": "🏠 %s  %d/%d players  %s",
		"需要更强": "Need stronger",
		"换取": "Trade",
		"第 1 回合 — %s 地下城": "Round 1 — %s dungeon",
		"奇物【%s】生效 — 补抽一张普通牌": "Relic [%s] active — draft 1 extra normal card",
		"替换装备: 槽位 %d → %s": "Replaced slot %d → %s",
		"装备 %s(%d/5)": "Equipped %s (%d/5)",
		"获得奇物【%s】%s": "Got relic [%s] %s",
		"%s 被击破! 回复 %d 生命": "%s defeated! Restored %d HP",
		"第 %d 回合开始": "Round %d begins",
		"BOSS 击破! 试炼通关!": "BOSS down! Trial cleared!",
		"复活币发光 — 你重新站了起来!": "Revive Coin glows — you rise again!",
		"第 %d 回合 — 二选一编成": "Round %d — draft 1 of 2",
		"%s 获得奇物【%s】": "%s got relic [%s]",
		"%s 装备 %s(%d/5)": "%s equipped %s (%d/5)",
		"对战开始 — %s 先攻": "Battle start — %s goes first",
		"%s 拿下第 %d 回合! (比分 %d:%d)": "%s takes round %d! (%d:%d)",
		"★ %s 赢得整场格斗对战!": "★ %s wins the duel!",
		"第 %d/%d 回合 · %s": "Round %d/%d · %s",
		"牌型 %s · %s": "Hand %s · %s",
		"装备后 %s": "Equips as %s",
		"替换后 %s": "Replaces as %s",
		"🟣 奇物已生效 — 补抽一张普通牌 (装备 %d/5)": "🟣 Relic active — draft 1 extra normal card (gear %d/5)",
		"第 %d 回合 — 二选一 (装备 %d/5)%s": "Round %d — pick 1 of 2 (gear %d/5)%s",
		"暴击 -%d": "CRIT -%d",
		"重击 -%d": "Heavy -%d",
		"荆棘 -%d": "Thorns -%d",
		"装备 %s": "Equip %s",
		"第 %d 回合 胜利!": "Round %d won!",
		"意图: %s": "Intent: %s",
		"%s 冷却 %d": "%s CD %d",
		"今日最佳: %s%s": "Today's best: %s%s",
		"通关! 剩余生命 %d%%": "Cleared! %d%% HP left",
		"到达第 %d 回合": "Reached round %d",
		" (新纪录!)": " (new record!)",
		"第 %d 回合 — 对战!": "Round %d — Battle!",
		"第 %d 回合 结束": "Round %d over",
		"回合胜 %d": "Round wins %d",
		"装备 %d/5 · 奇物 %d": "Gear %d/5 · Relics %d",
		"二选一 — 点选 1 张 (装备 %d/5%s)": "Pick 1 of 2 (gear %d/5%s)",
		"等待 %s 行动…": "Waiting for %s…",
		"%s 拿下本回合 — 即将进入下一回合…": "%s takes the round — next one coming…",
		"比分 %d : %d — 胜者 %s": "Score %d : %d — Winner %s",
		"奖励: %+d 金币 %+d 钻石 已入账": "Reward: +%d gold +%d diamonds added",
		"场次 %d · 胜 %d · 胜率 %d%%": "Matches %d · Wins %d · Win rate %d%%",
		"场次 %d · 胜 %d": "Matches %d · Wins %d",
		"共 %d 场 · 胜 %d 场 · 胜率 %d%% · 称号 %s": "%d matches · %d wins · %d%% win rate · Title %s",
		"⚔ 格斗试炼最高纪录: 第 %d 回合": "⚔ Fight Trials best: round %d",
		"已解锁 %d / %d": "Unlocked %d / %d",
		"全设备同一天同一布局, 冲击今日最佳成绩": "Same layout for everyone each day — beat your best!",
		"🔥 火球": "🔥 Fireball",
		"❄ 冰霜": "❄ Frost",
		"✟ 圣光": "✟ Holy",
		"⚡ 奥义": "⚡ Ultimate",
		"奥义 -%d": "ULT -%d",
		"稀有卡! 生命上限 +8%": "Rare! Max HP +8%",
		"稀有!": "RARE!",
		"COMBO x%d": "COMBO x%d",
		"勝利": "VICTORY",
		"敗北": "DEFEAT",
		"⚡ 蓄力中 — 全力输出(承伤 +50%)!": "⚡ Charging — burst it down (+50% dmg taken)!",
		"⚡ 敌人蓄力中…": "⚡ Enemy charging…",
		"BOSS 狂暴!": "BOSS ENRAGED!",
		"狂暴! 攻击大幅提升!": "Enraged! ATK greatly up!",
		"连击里程碑!": "Combo milestone!",
		"BOSS 击破! 可继续无尽挑战!": "BOSS down! Endless challenge unlocked!",
		"深入无尽挑战, 怪物每轮更强, 奖励随层数增长": "Deeper endless — stronger monsters, richer rewards",
		"继续无尽挑战": "Endless Challenge",
		"领奖结算": "Claim & Finish",
		"  评级 %s": "  Rank %s",
		"稀有卡! 生命上限永久 +8%": "Rare card! Max HP permanently +8%",
		"切换后全界面即时生效": "Applies to the whole UI instantly",
	},
	"zh_TW": {
		"⚔ 攻击": "⚔ 攻擊",
		"🛡 防御": "🛡 防禦",
		"✨ 技能": "✨ 技能",
		"✨技能": "✨技能",
		"🔥火球": "🔥火球",
		"❄冰霜": "❄冰霜",
		"✟圣光": "✟聖光",
		"冰霜": "冰霜",
		"圣光": "聖光",
		"火球": "火球",
		"玩家": "玩家",
		"(空位)": "(空位)",
		"(你)": "(你)",
		"← 主菜单": "← 主選單",
		"新手引导": "新手教學",
		"昵称": "暱稱",
		"普通模式": "經典模式",
		"肉鸽模式": "肉鴿模式",
		"格斗试炼": "格鬥試煉",
		"格斗": "格鬥",
		"每日挑战": "每日挑戰",
		"编成中…": "編成中…",
		"跳过这组": "跳過這組",
		"返 回": "返 回",
		"防御": "防禦",
		"AI 难度": "AI 難度",
		"IP 或域名": "IP 或網域",
		"▶ 当前回合": "▶ 當前回合",
		"⚔ 格斗试炼": "⚔ 格鬥試煉",
		"❄ 冻结": "❄ 凍結",
		"❄ 被冻结": "❄ 被凍結",
		"⬇ 一键下载": "⬇ 一鍵下載",
		"⬇ 发现新版本, 点击更新": "⬇ 發現新版本, 點擊更新",
		"一回合": "一回合",
		"三回合": "三回合",
		"五回合": "五回合",
		"不占装备槽": "不佔裝備槽",
		"与服务器断开, 自动重连中…": "與伺服器斷線, 自動重連中…",
		"两位格斗者正在编成…": "兩位格鬥者正在編成…",
		"个 人 档 案": "個 人 檔 案",
		"主机在线, 联机协商中… 若 15 秒后仍未进入, 请点【连接】重试": "主機在線, 連線協商中… 若 15 秒後仍未進入, 請點【連接】重試",
		"今日未挑战": "今日未挑戰",
		"保存并关闭": "儲存並關閉",
		"保存设置": "儲存設定",
		"全屏": "全螢幕",
		"分辨率": "解析度",
		"剪贴板中没有有效的邀请码(请先复制房主发的邀请信息)": "剪貼簿中沒有有效的邀請碼(請先複製房主發的邀請訊息)",
		"加入": "加入",
		"化身头像人物, 五回合二选一编成 5 张装备, 决战 BOSS": "化身頭像人物, 五回合二選一編成 5 張裝備, 決戰 BOSS",
		"和朋友开一局: 联机游戏 → 创建房间 → 把房间码发给朋友": "和朋友開一局: 連線遊戲 → 建立房間 → 把房間碼發給朋友",
		"商　城": "商　城",
		"回合数": "回合數",
		"回合胜 0": "回合勝 0",
		"回合胜利!": "回合勝利!",
		"回合落败": "回合落敗",
		"图像": "圖像",
		"垂直同步": "垂直同步",
		"复制邀请码": "複製邀請碼",
		"大富豪": "大富豪",
		"奇物(特殊牌不占槽)": "奇物(特殊牌不佔槽)",
		"对局已结束 — 可等待房主开始下一局": "對局已結束 — 可等待房主開始下一局",
		"对方": "對方",
		"已复制: ": "已複製: ",
		"已编成": "已編成",
		"已编成 — 等待对手…": "已編成 — 等待對手…",
		"已解锁": "已解鎖",
		"已连接! 选一个方式开局吧": "已連線! 選一個方式開局吧",
		"已领取": "已領取",
		"带王": "帶王",
		"应用分辨率": "套用解析度",
		"开始游戏": "開始遊戲",
		"成  就": "成  就",
		"成就·战绩": "成就·戰績",
		"或输入房间码": "或輸入房間碼",
		"战  绩": "戰  績",
		"房主": "房主",
		"房间": "房間",
		"技能": "技能",
		"放弃试炼": "放棄試煉",
		"无法发起连接探测, 请检查网络": "無法發起連線探測, 請檢查網路",
		"普通": "普通",
		"服务器": "伺服器",
		"服务器版本更高, 请更新客户端": "伺服器版本較新, 請更新用戶端",
		"未安装或未启动": "未安裝或未啟動",
		"未完成": "未完成",
		"未检测到局域网/Tailscale 地址": "未偵測到區域網路/Tailscale 位址",
		"未解锁": "未解鎖",
		"未连接服务器(127.0.0.1 只是本机地址)。\n同一 WiFi: 点【本机开房】, 朋友在【搜索附近主机】一键加入;\n跨网联机: 安装并登录 Tailscale 后用邀请码开局。": "未連線伺服器(127.0.0.1 只是本機位址)。\n同一 WiFi: 點【本機開房】, 朋友在【搜尋附近主機】一鍵加入;\n跨網連線: 安裝並登入 Tailscale 後用邀請碼開局。",
		"本地游戏": "本機遊戲",
		"本机服务器已启动": "本機伺服器已啟動",
		"格斗位": "格鬥位",
		"格斗对战": "格鬥對戰",
		"格斗对战(2人)": "格鬥對戰(2人)",
		"格斗者": "格鬥者",
		"检测中…": "偵測中…",
		"槽满: 立即生效": "槽滿: 立即生效",
		"模式": "模式",
		"每局『命运二选一』定规则: 10 种命运卡随机登场": "每局『命運二選一』定規則: 10 種命運卡隨機登場",
		"每日 0 点重置 · 完成对局与任务可获金币钻石": "每日 0 點重置 · 完成對局與任務可獲金幣鑽石",
		"每日任务": "每日任務",
		"没有可移除的玩家(仅房主可移除非自己的人类玩家)": "沒有可移除的玩家(僅房主可移除非自己的人類玩家)",
		"点【复制邀请码】发给朋友 → 朋友点【粘贴邀请码, 一键加入】或【搜索附近主机】": "點【複製邀請碼】發給朋友 → 朋友點【貼上邀請碼, 一鍵加入】或【搜尋附近主機】",
		"留在房间": "留在房間",
		"离开": "離開",
		"离开房间": "離開房間",
		"离线·AI 代管": "離線·AI 代管",
		"移除玩家": "移除玩家",
		"空位加AI": "空位加AI",
		"端口需为 1-65535 的数字": "連接埠需為 1-65535 的數字",
		"等待加入": "等待加入",
		"等待服务器…": "等待伺服器…",
		"签 到 领 取": "簽 到 領 取",
		"签到": "簽到",
		"简单": "簡單",
		"精英怪": "精英怪",
		"终 局": "終 局",
		"终局": "終局",
		"经典大富豪: 换牌 / 革命 / 8切, 回合制排名结算": "經典大富豪: 換牌 / 革命 / 8切, 回合制排名結算",
		"统  计": "統  計",
		"联机准备 · Tailscale": "連線準備 · Tailscale",
		"联机对战": "連線對戰",
		"联机游戏": "連線遊戲",
		"胜 利 !": "勝 利 !",
		"装备 0/5 · 奇物 0": "裝備 0/5 · 奇物 0",
		"装备槽": "裝備槽",
		"装备槽已满 — 点上方要替换的槽位，或跳过": "裝備槽已滿 — 點上方要替換的槽位, 或跳過",
		"装备槽已满 — 点击左上要替换的槽位，或跳过": "裝備槽已滿 — 點擊左上要替換的槽位, 或跳過",
		"观战中": "觀戰中",
		"观战位": "觀戰位",
		"规则设置": "規則設定",
		"触感": "觸感",
		"设  置": "設  置",
		"设　置": "設　置",
		"试炼结束": "試煉結束",
		"试炼通关!": "試煉通關!",
		"请输入服务器地址": "請輸入伺服器位址",
		"败 北…": "敗 北…",
		"输赢": "輸贏",
		"返回大厅": "返回大廳",
		"返回菜单": "返回選單",
		"还没有对局记录 — 去打一局吧!": "還沒有對局記錄 — 去打一局吧!",
		"连接": "連接",
		"退出游戏": "退出遊戲",
		"选择游戏模式": "選擇遊戲模式",
		"选牌中…": "選牌中…",
		"附近主机(同一 WiFi)": "附近主機(同一 WiFi)",
		"集齐 5 张触发牌型协同": "集齊 5 張觸發牌型協同",
		"震动反馈(轮到你/结算)": "震動回饋(輪到你/結算)",
		"革命": "革命",
		"音乐": "音樂",
		"音效": "音效",
		"音量": "音量",
		"领 取": "領 取",
		"，本回合有额外候选组!": ",本回合有額外候選組!",
		"，额外候选组!": ",額外候選組!",
		"🂡 大富豪": "🂡 大富豪",
		"🎲  快速匹配": "🎲  快速配對",
		"🎲 肉鸽模式": "🎲 肉鴿模式",
		"🏠  创建房间": "🏠  建立房間",
		"🏠 本机开房(当主机)": "🏠 本機開房(當主機)",
		"👁 观战中 — 本房间仅 1/2 号位可出战": "👁 觀戰中 — 本房間僅 1/2 號位可出戰",
		"💥 重击(防御可减!)": "💥 重擊(防禦可減!)",
		"📅 每日挑战": "📅 每日挑戰",
		"📋 粘贴邀请码, 一键加入": "📋 貼上邀請碼, 一鍵加入",
		"📕 命运卡图鉴": "📕 命運卡圖鑑",
		"🔍 搜索附近主机": "🔍 搜尋附近主機",
		"🔥 法术(魔抗可减!)": "🔥 法術(魔抗可減!)",
		"🟣 奇物生效! 补抽一张普通牌": "🟣 奇物生效! 補抽一張普通牌",
		"🥊 联机格斗对战": "🥊 連線格鬥對戰",
		"同一 WiFi 的朋友: 联机页点【搜索附近主机】一键加入\n异地朋友: 点【复制邀请码】发给他(含全部地址)": "同一 WiFi 的朋友: 連線頁點【搜尋附近主機】一鍵加入\n異地朋友: 點【複製邀請碼】發給他(含全部位址)",
		"Tailscale 已就绪 — 点【本机开房】创建房间, 把邀请码发给朋友;\n或点【粘贴邀请码, 一键加入】朋友的主机。": "Tailscale 已就緒 — 點【本機開房】建立房間, 把邀請碼發給朋友;\n或點【貼上邀請碼, 一鍵加入】朋友的主機。",
		"复活币生效!": "復活幣生效!",
		"第 1 回合 — %s 地下城": "第 1 回合 — %s 地下城",
		"奇物【%s】生效 — 补抽一张普通牌": "奇物【%s】生效 — 補抽一張普通牌",
		"替换装备: 槽位 %d → %s": "替換裝備: 槽位 %d → %s",
		"装备 %s(%d/5)": "裝備 %s(%d/5)",
		"获得奇物【%s】%s": "獲得奇物【%s】%s",
		"第 %d 回合 %s: %s 出现! HP %d / 攻击 %d": "第 %d 回合 %s: %s 出現! HP %d / 攻擊 %d",
		"%s 被击破! 回复 %d 生命": "%s 被擊破! 回復 %d 生命",
		"第 %d 回合开始": "第 %d 回合開始",
		"BOSS 击破! 试炼通关!": "BOSS 擊破! 試煉通關!",
		"复活币发光 — 你重新站了起来!": "復活幣發光 — 你重新站了起來!",
		"第 %d 回合 — 二选一编成": "第 %d 回合 — 二選一編成",
		"%s 获得奇物【%s】": "%s 獲得奇物【%s】",
		"%s 装备 %s(%d/5)": "%s 裝備 %s(%d/5)",
		"对战开始 — %s 先攻": "對戰開始 — %s 先攻",
		"%s 拿下第 %d 回合! (比分 %d:%d)": "%s 拿下第 %d 回合! (比分 %d:%d)",
		"★ %s 赢得整场格斗对战!": "★ %s 贏得整場格鬥對戰!",
		"第 %d/%d 回合 · %s": "第 %d/%d 回合 · %s",
		"牌型 %s · %s": "牌型 %s · %s",
		"装备后 %s": "裝備後 %s",
		"替换后 %s": "替換後 %s",
		"🟣 奇物已生效 — 补抽一张普通牌 (装备 %d/5)": "🟣 奇物已生效 — 補抽一張普通牌 (裝備 %d/5)",
		"第 %d 回合 — 二选一 (装备 %d/5)%s": "第 %d 回合 — 二選一 (裝備 %d/5)%s",
		"暴击 -%d": "暴擊 -%d",
		"重击 -%d": "重擊 -%d",
		"荆棘 -%d": "荊棘 -%d",
		"装备 %s": "裝備 %s",
		"第 %d 回合 胜利!": "第 %d 回合 勝利!",
		"意图: %s": "意圖: %s",
		"%s 冷却 %d": "%s 冷卻 %d",
		"通过 %d/5 回合 · 历史最佳第 %d 层\n奖励: %d 钻石 已入账": "通過 %d/5 回合 · 歷史最佳第 %d 層\n獎勵: %d 鑽石 已入帳",
		"今日最佳: %s%s": "今日最佳: %s%s",
		"通关! 剩余生命 %d%%": "通關! 剩餘生命 %d%%",
		"到达第 %d 回合": "到達第 %d 回合",
		" (新纪录!)": " (新紀錄!)",
		"每日挑战通关!": "每日挑戰通關!",
		"每日挑战结束": "每日挑戰結束",
		"第 %d 回合 — 对战!": "第 %d 回合 — 對戰!",
		"第 %d 回合 结束": "第 %d 回合 結束",
		"回合胜 %d": "回合勝 %d",
		"装备 %d/5 · 奇物 %d": "裝備 %d/5 · 奇物 %d",
		"二选一 — 点选 1 张 (装备 %d/5%s)": "二選一 — 點選 1 張 (裝備 %d/5%s)",
		"等待 %s 行动…": "等待 %s 行動…",
		"%s 拿下本回合 — 即将进入下一回合…": "%s 拿下本回合 — 即將進入下一回合…",
		"比分 %d : %d — 胜者 %s": "比分 %d : %d — 勝者 %s",
		"奖励: %+d 金币 %+d 钻石 已入账": "獎勵: %+d 金幣 %+d 鑽石 已入帳",
		"场次 %d · 胜 %d · 胜率 %d%%": "場次 %d · 勝 %d · 勝率 %d%%",
		"场次 %d · 胜 %d": "場次 %d · 勝 %d",
		"局数 %d · 通关 %d · 最远第 %d 回合 · 击破 BOSS %d": "局數 %d · 通關 %d · 最遠第 %d 回合 · 擊破 BOSS %d",
		"胜场 %d": "勝場 %d",
		"今日已通关(剩余生命 %d%%)": "今日已通關(剩餘生命 %d%%)",
		"今日最佳: 到达第 %d 回合": "今日最佳: 到達第 %d 回合",
		"累计参与 %d 天": "累計參與 %d 天",
		"已见 %d / %d 种": "已見 %d / %d 種",
		"共 %d 场 · 胜 %d 场 · 胜率 %d%% · 称号 %s": "共 %d 場 · 勝 %d 場 · 勝率 %d%% · 稱號 %s",
		"⚔ 格斗试炼最高纪录: 第 %d 回合": "⚔ 格鬥試煉最高紀錄: 第 %d 回合",
		"已解锁 %d / %d": "已解鎖 %d / %d",
		"全设备同一天同一布局, 冲击今日最佳成绩": "全設備同一天同一布局, 衝擊今日最佳成績",
		"🔥 火球": "🔥 火球",
		"❄ 冰霜": "❄ 冰霜",
		"✟ 圣光": "✟ 聖光",
		"⚡ 奥义": "⚡ 奧義",
		"奥义 -%d": "奧義 -%d",
		"完美格挡! 反击 -%d": "完美格擋! 反擊 -%d",
		"稀有卡! 生命上限 +8%": "稀有卡! 生命上限 +8%",
		"稀有!": "稀有!",
		"COMBO x%d": "連擊 x%d",
		"人 物 皮 肤": "人 物 皮 膚",
		"卡 牌 面 貌": "卡 牌 面 貌",
		"特 殊 道 具": "特 殊 道 具",
		"装 备": "裝 備",
		"购 买": "購 買",
		"已拥有": "已擁有",
		"使用中": "使用中",
		"购买成功, 已生效!": "購買成功, 已生效!",
		"购买成功, 已装备!": "購買成功, 已裝備!",
		"余额不足, 先去赚一赚吧": "餘額不足, 先去賺一賺吧",
		"生效中·今日": "生效中·今日",
		"勝利": "勝利",
		"敗北": "敗北",
		"⚡ 蓄力中 — 全力输出(承伤 +50%)!": "⚡ 蓄力中 — 全力輸出(承傷 +50%)!",
		"⚡ 敌人蓄力中…": "⚡ 敵人蓄力中…",
		"BOSS 狂暴!": "BOSS 狂暴!",
		"狂暴! 攻击大幅提升!": "狂暴! 攻擊大幅提升!",
		"连击里程碑!": "連擊里程碑!",
		"BOSS 击破! 可继续无尽挑战!": "BOSS 擊破! 可繼續無盡挑戰!",
		"深入无尽挑战, 怪物每轮更强, 奖励随层数增长": "深入無盡挑戰, 怪物每輪更強, 獎勵隨層數增長",
		"继续无尽挑战": "繼續無盡挑戰",
		"领奖结算": "領獎結算",
		"  评级 %s": "  評級 %s",
		"稀有卡! 生命上限永久 +8%": "稀有卡! 生命上限永久 +8%",
		"切换后全界面即时生效": "切換後全介面即時生效",
	},
	"ja": {
		"⚔ 攻击": "⚔ 攻撃",
		"🛡 防御": "🛡 防御",
		"✨ 技能": "✨ スキル",
		"✨技能": "✨スキル",
		"🔥火球": "🔥火球",
		"❄冰霜": "❄氷結",
		"✟圣光": "✟聖光",
		"冰霜": "氷結",
		"圣光": "聖光",
		"火球": "火球",
		"玩家": "プレイヤー",
		"(空位)": "(空席)",
		"(你)": "(あなた)",
		"← 主菜单": "← メインメニュー",
		"新手引导": "チュートリアル",
		"昵称": "ニックネーム",
		"普通模式": "ノーマル",
		"肉鸽模式": "ローグ",
		"格斗试炼": "格闘試練",
		"格斗": "格闘",
		"每日挑战": "デイリー挑戦",
		"编成中…": "編成中…",
		"跳过这组": "この組をスキップ",
		"返 回": "戻 る",
		"防御": "防御",
		"AI 难度": "AI 難易度",
		"IP 或域名": "IP またはドメイン",
		"▶ 当前回合": "▶ 現在のターン",
		"⚔ 格斗试炼": "⚔ 格闘試練",
		"❄ 冻结": "❄ 凍結",
		"❄ 被冻结": "❄ 凍結状態",
		"⬇ 一键下载": "⬇ ワンクリック DL",
		"⬇ 发现新版本, 点击更新": "⬇ 新バージョンあり, タップで更新",
		"一回合": "1 回戦",
		"三回合": "3 回戦",
		"五回合": "5 回戦",
		"不占装备槽": "装備枠を使わない",
		"与服务器断开, 自动重连中…": "サーバー切断, 自動再接続中…",
		"两位格斗者正在编成…": "両ファイターが編成中…",
		"个 人 档 案": "プロフィール",
		"主机在线, 联机协商中… 若 15 秒后仍未进入, 请点【连接】重试": "ホスト online, 接続交渉中… 15 秒経っても入場できない場合は【接続】を再試行",
		"今日未挑战": "本日は未挑戦",
		"保存并关闭": "保存して閉じる",
		"保存设置": "設定を保存",
		"全屏": "フルスクリーン",
		"分辨率": "解像度",
		"剪贴板中没有有效的邀请码(请先复制房主发的邀请信息)": "クリップボードに有効な招待コードがありません(先に招待情報をコピーしてください)",
		"加入": "参加",
		"化身头像人物, 五回合二选一编成 5 张装备, 决战 BOSS": "アバターとなり 5 回戦の二択で装備 5 枚を編成, BOSS 戦へ",
		"和朋友开一局: 联机游戏 → 创建房间 → 把房间码发给朋友": "友達と対戦: オンライン → 部屋を作成 → 部屋コードを送る",
		"商　城": "ショップ",
		"回合数": "回戦数",
		"回合胜 0": "ラウンド勝 0",
		"回合胜利!": "ラウンド勝利!",
		"回合落败": "ラウンド敗北",
		"图像": "グラフィック",
		"垂直同步": "垂直同期",
		"复制邀请码": "招待コードをコピー",
		"大富豪": "大富豪",
		"奇物(特殊牌不占槽)": "レリック(特殊カードは枠外)",
		"对局已结束 — 可等待房主开始下一局": "対局終了 — ホストの次の開始を待てます",
		"对方": "相手",
		"已复制: ": "コピーしました: ",
		"已编成": "編成済",
		"已编成 — 等待对手…": "編成済 — 相手を待機中…",
		"已解锁": "解放済み",
		"已连接! 选一个方式开局吧": "接続完了! 開始方法を選ぼう",
		"已领取": "受取済み",
		"带王": "ジョーカーあり",
		"应用分辨率": "解像度を適用",
		"开始游戏": "ゲーム開始",
		"成  就": "実  績",
		"成就·战绩": "実績・戦績",
		"或输入房间码": "または部屋コード入力",
		"战  绩": "戦  績",
		"房主": "ホスト",
		"房间": "部屋",
		"技能": "スキル",
		"放弃试炼": "試練を断念",
		"无法发起连接探测, 请检查网络": "接続探测できません, ネットワークを確認",
		"普通": "普通",
		"服务器": "サーバー",
		"服务器版本更高, 请更新客户端": "サーバーが新しいバージョンです, 更新してください",
		"未安装或未启动": "未インストールまたは未起動",
		"未完成": "未達成",
		"未检测到局域网/Tailscale 地址": "LAN/Tailscale アドレスが見つかりません",
		"未解锁": "未解放",
		"未连接服务器(127.0.0.1 只是本机地址)。\n同一 WiFi: 点【本机开房】, 朋友在【搜索附近主机】一键加入;\n跨网联机: 安装并登录 Tailscale 后用邀请码开局。": "サーバー未接続(127.0.0.1 はローカルのみ)。\n同一 WiFi: 【ローカルホスト】をタップ, 友達は【近くのホスト】で参加;\n別回線: Tailscale にログイン後, 招待コードで開始。",
		"本地游戏": "ローカル対局",
		"本机服务器已启动": "ローカルサーバー起動済み",
		"格斗位": "ファイター席",
		"格斗对战": "格闘対戦",
		"格斗对战(2人)": "格闘対戦(2人)",
		"格斗者": "ファイター",
		"检测中…": "確認中…",
		"槽满: 立即生效": "枠満杯: 即時発動",
		"模式": "モード",
		"每局『命运二选一』定规则: 10 种命运卡随机登场": "毎試合『運命の二択』でルール決定: 10 種の運命カードがランダム登場",
		"每日 0 点重置 · 完成对局与任务可获金币钻石": "毎日 0 時にリセット · 対局とミッションでコインとダイヤ獲得",
		"每日任务": "デイリー任務",
		"没有可移除的玩家(仅房主可移除非自己的人类玩家)": "削除できるプレイヤーがいません(ホストのみ他プレイヤーを削除可)",
		"点【复制邀请码】发给朋友 → 朋友点【粘贴邀请码, 一键加入】或【搜索附近主机】": "【招待コードをコピー】して友達へ → 友達は【貼り付けで参加】または【近くのホスト】",
		"留在房间": "部屋に残る",
		"离开": "退出",
		"离开房间": "部屋を退出",
		"离线·AI 代管": " offline·AI 代行",
		"移除玩家": "プレイヤーを削除",
		"空位加AI": "空席に AI",
		"端口需为 1-65535 的数字": "ポートは 1-65535 の数字",
		"等待加入": "参加待ち",
		"等待服务器…": "サーバー待機中…",
		"签 到 领 取": "受  取",
		"签到": "サインイン",
		"简单": "かんたん",
		"精英怪": "エリート",
		"终 局": "決  着",
		"终局": "決着",
		"经典大富豪: 换牌 / 革命 / 8切, 回合制排名结算": "大富豪: 交換 / 革命 / 8切り, ランク制得点",
		"统  计": "統  計",
		"联机准备 · Tailscale": "オンライン準備 · Tailscale",
		"联机对战": "オンライン対戦",
		"联机游戏": "オンライン",
		"胜 利 !": "勝  利 !",
		"装备 0/5 · 奇物 0": "装備 0/5 · レリック 0",
		"装备槽": "装備枠",
		"装备槽已满 — 点上方要替换的槽位，或跳过": "装備枠満杯 — 上の枠をタップして交換, またはスキップ",
		"装备槽已满 — 点击左上要替换的槽位，或跳过": "装備枠満杯 — 左上の枠をタップして交換, またはスキップ",
		"观战中": "観戦中",
		"观战位": "観戦席",
		"规则设置": "ルール設定",
		"触感": "振動",
		"设  置": "設  定",
		"设　置": "設　定",
		"试炼结束": "試練終了",
		"试炼通关!": "試練制覇!",
		"请输入服务器地址": "サーバーアドレスを入力",
		"败 北…": "敗  北…",
		"输赢": "レート",
		"返回大厅": "ロビーへ戻る",
		"返回菜单": "メニューへ戻る",
		"还没有对局记录 — 去打一局吧!": "対局記録がありません — プレイしよう!",
		"连接": "接続",
		"退出游戏": "ゲーム終了",
		"选择游戏模式": "ゲームモード選択",
		"选牌中…": "選択中…",
		"附近主机(同一 WiFi)": "近くのホスト(同一 WiFi)",
		"集齐 5 张触发牌型协同": "5 枚集めて役シナジー発動",
		"震动反馈(轮到你/结算)": "振動フィードバック(自分のターン/結果)",
		"革命": "革命",
		"音乐": "音楽",
		"音效": "効果音",
		"音量": "音量",
		"领 取": "受  取",
		"，本回合有额外候选组!": ",このラウンドは追加候補あり!",
		"，额外候选组!": ",追加候補あり!",
		"🂡 大富豪": "🂡 大富豪",
		"🎲  快速匹配": "🎲  クイックマッチ",
		"🎲 肉鸽模式": "🎲 ローグ",
		"🏠  创建房间": "🏠  部屋を作成",
		"🏠 本机开房(当主机)": "🏠 ローカルホスト",
		"👁 观战中 — 本房间仅 1/2 号位可出战": "👁 観戦中 — この部屋は 1/2 番席のみ出撃可",
		"💥 重击(防御可减!)": "💥 強打(防御で軽減!)",
		"📅 每日挑战": "📅 デイリー挑戦",
		"📋 粘贴邀请码, 一键加入": "📋 招待コードを貼り付け",
		"📕 命运卡图鉴": "📕 運命カード図鑑",
		"🔍 搜索附近主机": "🔍 近くのホストを検索",
		"🔥 法术(魔抗可减!)": "🔥 魔法(魔法耐性で軽減!)",
		"🟣 奇物生效! 补抽一张普通牌": "🟣 レリック発動! 通常カードを 1 枚追加 draft",
		"🥊 联机格斗对战": "🥊 オンライン格闘対戦",
		"同一 WiFi 的朋友: 联机页点【搜索附近主机】一键加入\n异地朋友: 点【复制邀请码】发给他(含全部地址)": "同一 WiFi の友達: オンライン頁の【近くのホスト】でワンタップ参加\n遠隔の友達: 【招待コードをコピー】を送る(全アドレス含む)",
		"Tailscale 已就绪 — 点【本机开房】创建房间, 把邀请码发给朋友;\n或点【粘贴邀请码, 一键加入】朋友的主机。": "Tailscale 準備完了 — 【ローカルホスト】で部屋を作り招待コードを送る;\nまたは【貼り付けで参加】で友達のホストへ。",
		"复活币生效!": "復活コイン発動!",
		"第 1 回合 — %s 地下城": "ラウンド1 — %s のダンジョン",
		"奇物【%s】生效 — 补抽一张普通牌": "レリック【%s】発動 — 通常カードを 1 枚追加",
		"替换装备: 槽位 %d → %s": "装備交換: 枠 %d → %s",
		"装备 %s(%d/5)": "装備 %s(%d/5)",
		"获得奇物【%s】%s": "レリック【%s】%s を獲得",
		"第 %d 回合 %s: %s 出现! HP %d / 攻击 %d": "第 %d ラウンド %s: %s 出現! HP %d / 攻撃 %d",
		"%s 被击破! 回复 %d 生命": "%s を撃破! HP %d 回復",
		"第 %d 回合开始": "第 %d ラウンド開始",
		"BOSS 击破! 试炼通关!": "BOSS 撃破! 試練制覇!",
		"复活币发光 — 你重新站了起来!": "復活コインが光る — あなたは立ち上がった!",
		"第 %d 回合 — 二选一编成": "第 %d ラウンド — 二択編成",
		"%s 获得奇物【%s】": "%s がレリック【%s】を獲得",
		"%s 装备 %s(%d/5)": "%s が装備 %s(%d/5)",
		"对战开始 — %s 先攻": "バトル開始 — %s が先攻",
		"%s 拿下第 %d 回合! (比分 %d:%d)": "%s が第 %d ラウンド獲得! (%d:%d)",
		"★ %s 赢得整场格斗对战!": "★ %s が対戦に勝利した!",
		"第 %d/%d 回合 · %s": "第 %d/%d ラウンド · %s",
		"牌型 %s · %s": "役 %s · %s",
		"装备后 %s": "装備すると %s",
		"替换后 %s": "交換すると %s",
		"🟣 奇物已生效 — 补抽一张普通牌 (装备 %d/5)": "🟣 レリック発動 — 通常カードを 1 枚追加 (装備 %d/5)",
		"第 %d 回合 — 二选一 (装备 %d/5)%s": "第 %d ラウンド — 二択 (装備 %d/5)%s",
		"暴击 -%d": "クリティカル -%d",
		"重击 -%d": "強打 -%d",
		"荆棘 -%d": "とげ -%d",
		"装备 %s": "装備 %s",
		"第 %d 回合 胜利!": "第 %d ラウンド 勝利!",
		"意图: %s": "意図: %s",
		"%s 冷却 %d": "%s クールダウン %d",
		"通过 %d/5 回合 · 历史最佳第 %d 层\n奖励: %d 钻石 已入账": "%d/5 ラウンド通過 · ベスト第 %d 層\n報酬: ダイヤ %d 入帳",
		"今日最佳: %s%s": "今日のベスト: %s%s",
		"通关! 剩余生命 %d%%": "クリア! 残り HP %d%%",
		"到达第 %d 回合": "第 %d ラウンド到達",
		" (新纪录!)": " (新記録!)",
		"每日挑战通关!": "デイリー制覇!",
		"每日挑战结束": "デイリー終了",
		"第 %d 回合 — 对战!": "第 %d ラウンド — バトル!",
		"第 %d 回合 结束": "第 %d ラウンド終了",
		"回合胜 %d": "ラウンド勝 %d",
		"装备 %d/5 · 奇物 %d": "装備 %d/5 · レリック %d",
		"二选一 — 点选 1 张 (装备 %d/5%s)": "二択 — 1 枚選択 (装備 %d/5%s)",
		"等待 %s 行动…": "%s の行動待ち…",
		"%s 拿下本回合 — 即将进入下一回合…": "%s がこのラウンド獲得 — 次へ…",
		"比分 %d : %d — 胜者 %s": "スコア %d : %d — 勝者 %s",
		"奖励: %+d 金币 %+d 钻石 已入账": "報酬: +%d コイン +%d ダイヤ 入帳",
		"场次 %d · 胜 %d · 胜率 %d%%": "対局 %d · 勝 %d · 勝率 %d%%",
		"场次 %d · 胜 %d": "対局 %d · 勝 %d",
		"局数 %d · 通关 %d · 最远第 %d 回合 · 击破 BOSS %d": "プレイ %d · クリア %d · 最深ラウンド %d · BOSS %d",
		"胜场 %d": "勝利 %d",
		"今日已通关(剩余生命 %d%%)": "今日クリア済み(残り HP %d%%)",
		"今日最佳: 到达第 %d 回合": "今日のベスト: 第 %d ラウンド",
		"累计参与 %d 天": "累計 %d 日参加",
		"已见 %d / %d 种": "未遭遇 %d / %d 種",
		"共 %d 场 · 胜 %d 场 · 胜率 %d%% · 称号 %s": "計 %d 戦 · %d 勝 · 勝率 %d%% · 称号 %s",
		"⚔ 格斗试炼最高纪录: 第 %d 回合": "⚔ 格闘試練ベスト: 第 %d ラウンド",
		"已解锁 %d / %d": "解放 %d / %d",
		"全设备同一天同一布局, 冲击今日最佳成绩": "全デバイス同日 same 構成, 今日のベストを狙え",
		"🔥 火球": "🔥火球",
		"❄ 冰霜": "❄氷結",
		"✟ 圣光": "✟聖光",
		"⚡ 奥义": "⚡奥義",
		"奥义 -%d": "奥義 -%d",
		"完美格挡! 反击 -%d": "パリィ! 反撃 -%d",
		"稀有卡! 生命上限 +8%": "レア! 最大 HP +8%",
		"稀有!": "レア!",
		"COMBO x%d": "コンボ x%d",
		"人 物 皮 肤": "キャラクタースキン",
		"卡 牌 面 貌": "カードデッキ",
		"特 殊 道 具": "スペシャルアイテム",
		"装 备": "装備",
		"购 买": "購入",
		"已拥有": "所持済み",
		"使用中": "使用中",
		"购买成功, 已生效!": "購入成功, 発動しました!",
		"购买成功, 已装备!": "購入成功, 装備しました!",
		"余额不足, 先去赚一赚吧": "残高不足 — まずは稼ごう",
		"生效中·今日": "本日発動中",
		"勝利": "勝利",
		"敗北": "敗北",
		"⚡ 蓄力中 — 全力输出(承伤 +50%)!": "⚡チャージ中 — 全力攻撃(被ダメ +50%)!",
		"⚡ 敌人蓄力中…": "⚡敵チャージ中…",
		"BOSS 狂暴!": "BOSS 狂暴化!",
		"狂暴! 攻击大幅提升!": "狂暴! 攻撃大幅アップ!",
		"连击里程碑!": "コンボマイルストーン!",
		"BOSS 击破! 可继续无尽挑战!": "BOSS 撃破! エンドレス挑戦へ!",
		"深入无尽挑战, 怪物每轮更强, 奖励随层数增长": "エンドレスへ — 強くなる敵, 増える報酬",
		"继续无尽挑战": "エンドレスへ",
		"领奖结算": "報酬を受け取る",
		"  评级 %s": "  ランク %s",
		"稀有卡! 生命上限永久 +8%": "レア! 最大 HP 永久 +8%",
		"切换后全界面即时生效": "切り替え後すぐに全 UI に反映",
	},
	"ko": {
		"⚔ 攻击": "⚔ 공격",
		"🛡 防御": "🛡 방어",
		"✨ 技能": "✨ 스킬",
		"✨技能": "✨스킬",
		"🔥火球": "🔥화염구",
		"❄冰霜": "❄서리",
		"✟圣光": "✟성광",
		"冰霜": "서리",
		"圣光": "성광",
		"火球": "화염구",
		"玩家": "플레이어",
		"(空位)": "(빈자리)",
		"(你)": "(나)",
		"← 主菜单": "← 메인 메뉴",
		"新手引导": "튜토리얼",
		"昵称": "닉네임",
		"普通模式": "클래식 모드",
		"肉鸽模式": "로그 모드",
		"格斗试炼": "파이트 트라이얼",
		"格斗": "격투",
		"每日挑战": "일일 챌린지",
		"编成中…": "편성 중…",
		"跳过这组": "이 조합 건너뛰기",
		"返 回": "돌 아",
		"防御": "방어",
		"AI 难度": "AI 난이도",
		"IP 或域名": "IP 또는 도메인",
		"▶ 当前回合": "▶ 현재 턴",
		"⚔ 格斗试炼": "⚔ 파이트 트라이얼",
		"❄ 冻结": "❄ 빙결",
		"❄ 被冻结": "❄ 빙결됨",
		"⬇ 一键下载": "⬇ 원클릭 다운로드",
		"⬇ 发现新版本, 点击更新": "⬇ 새 버전 발견, 탭하여 업데이트",
		"一回合": "1 라운드",
		"三回合": "3 라운드",
		"五回合": "5 라운드",
		"不占装备槽": "장비칸 미사용",
		"与服务器断开, 自动重连中…": "서버 연결 끊김, 자동 재접속 중…",
		"两位格斗者正在编成…": "양쪽 파이터 편성 중…",
		"个 人 档 案": "프로필",
		"主机在线, 联机协商中… 若 15 秒后仍未进入, 请点【连接】重试": "호스트 온라인, 협상 중… 15초 후에도 입장 못하면 [연결] 다시 시도",
		"今日未挑战": "오늘 미도전",
		"保存并关闭": "저장 후 닫기",
		"保存设置": "설정 저장",
		"全屏": "전체 화면",
		"分辨率": "해상도",
		"剪贴板中没有有效的邀请码(请先复制房主发的邀请信息)": "클립보드에 유효한 초대 코드가 없습니다(먼저 복사하세요)",
		"加入": "참가",
		"化身头像人物, 五回合二选一编成 5 张装备, 决战 BOSS": "아바타가 되어 5 라운드 택1으로 장비 5장 편성, BOSS전!",
		"和朋友开一局: 联机游戏 → 创建房间 → 把房间码发给朋友": "친구와 한 판: 온라인 → 방 만들기 → 방 코드 공유",
		"商　城": "상 점",
		"回合数": "라운드 수",
		"回合胜 0": "라운드 승 0",
		"回合胜利!": "라운드 승리!",
		"回合落败": "라운드 패배",
		"图像": "그래픽",
		"垂直同步": "수직 동기화",
		"复制邀请码": "초대 코드 복사",
		"大富豪": "대부호",
		"奇物(特殊牌不占槽)": "유물(특수 카드는 칸 미사용)",
		"对局已结束 — 可等待房主开始下一局": "경기 종료 — 방장의 다음 시작을 기다릴 수 있습니다",
		"对方": "상대",
		"已复制: ": "복사됨: ",
		"已编成": "편성 완료",
		"已编成 — 等待对手…": "편성 완료 — 상대 대기 중…",
		"已解锁": "해금됨",
		"已连接! 选一个方式开局吧": "연결됨! 시작 방식을 선택하세요",
		"已领取": "수령 완료",
		"带王": "조커 있음",
		"应用分辨率": "해상도 적용",
		"开始游戏": "게임 시작",
		"成  就": "업  적",
		"成就·战绩": "업적·전적",
		"或输入房间码": "또는 방 코드 입력",
		"战  绩": "전  적",
		"房主": "방장",
		"房间": "방",
		"技能": "스킬",
		"放弃试炼": "시련 포기",
		"无法发起连接探测, 请检查网络": "연결 확인 불가, 네트워크를 점검하세요",
		"普通": "보통",
		"服务器": "서버",
		"服务器版本更高, 请更新客户端": "서버 버전이 더 높습니다, 클라이언트를 업데이트하세요",
		"未安装或未启动": "미설치 또는 미실행",
		"未完成": "미완료",
		"未检测到局域网/Tailscale 地址": "LAN/Tailscale 주소를 찾지 못했습니다",
		"未解锁": "미해금",
		"未连接服务器(127.0.0.1 只是本机地址)。\n同一 WiFi: 点【本机开房】, 朋友在【搜索附近主机】一键加入;\n跨网联机: 安装并登录 Tailscale 后用邀请码开局。": "서버 미연결(127.0.0.1은 본기기 전용)。\n같은 WiFi: [로컬 호스트] 탭, 친구는 [근처 호스트]로 참가;\n타 네트워크: Tailscale 로그인 후 초대 코드로 시작。",
		"本地游戏": "로컬 게임",
		"本机服务器已启动": "로컬 서버 시작됨",
		"格斗位": "파이터석",
		"格斗对战": "파이트 대전",
		"格斗对战(2人)": "파이트 대전(2인)",
		"格斗者": "파이터",
		"检测中…": "확인 중…",
		"槽满: 立即生效": "칸 만석: 즉시 발동",
		"模式": "모드",
		"每局『命运二选一』定规则: 10 种命运卡随机登场": "매 판 [운명 택1]으로 규칙 결정: 10종 운명 카드 랜덤 등장",
		"每日 0 点重置 · 完成对局与任务可获金币钻石": "매일 0시 리셋 · 대국과 미션으로 코인과 다이아 획득",
		"每日任务": "일일 미션",
		"没有可移除的玩家(仅房主可移除非自己的人类玩家)": "제거할 플레이어가 없습니다(방장만 다른 인간 플레이어 제거 가능)",
		"点【复制邀请码】发给朋友 → 朋友点【粘贴邀请码, 一键加入】或【搜索附近主机】": "[초대 코드 복사]로 공유 → 친구는 [붙여넣기 참가] 또는 [근처 호스트]",
		"留在房间": "방에 머무르기",
		"离开": "나가기",
		"离开房间": "방 나가기",
		"离线·AI 代管": "오프라인·AI 대행",
		"移除玩家": "플레이어 제거",
		"空位加AI": "빈자리 AI 추가",
		"端口需为 1-65535 的数字": "포트는 1-65535 숫자",
		"等待加入": "참가 대기",
		"等待服务器…": "서버 대기 중…",
		"签 到 领 取": "출 석 수 령",
		"签到": "출석 체크",
		"简单": "쉬움",
		"精英怪": "엘리트",
		"终 局": "결  착",
		"终局": "결착",
		"经典大富豪: 换牌 / 革命 / 8切, 回合制排名结算": "대부호: 교환 / 혁명 / 8컷, 랭크제 점수",
		"统  计": "통  계",
		"联机准备 · Tailscale": "온라인 준비 · Tailscale",
		"联机对战": "온라인 대전",
		"联机游戏": "온라인 게임",
		"胜 利 !": "승  리 !",
		"装备 0/5 · 奇物 0": "장비 0/5 · 유물 0",
		"装备槽": "장비칸",
		"装备槽已满 — 点上方要替换的槽位，或跳过": "장비칸 만석 — 위의 칸을 탭해 교체하거나 건너뛰기",
		"装备槽已满 — 点击左上要替换的槽位，或跳过": "장비칸 만석 — 좌상단 칸을 탭해 교체하거나 건너뛰기",
		"观战中": "관전 중",
		"观战位": "관전석",
		"规则设置": "규칙 설정",
		"触感": "진동",
		"设  置": "설  정",
		"设　置": "설　정",
		"试炼结束": "시련 종료",
		"试炼通关!": "시련 클리어!",
		"请输入服务器地址": "서버 주소를 입력하세요",
		"败 北…": "패  배…",
		"输赢": "판돈",
		"返回大厅": "로비로",
		"返回菜单": "메뉴로",
		"还没有对局记录 — 去打一局吧!": "대국 기록이 없습니다 — 한 판 하러 가요!",
		"连接": "연결",
		"退出游戏": "게임 종료",
		"选择游戏模式": "게임 모드 선택",
		"选牌中…": "카드 선택 중…",
		"附近主机(同一 WiFi)": "근처 호스트(같은 WiFi)",
		"集齐 5 张触发牌型协同": "5장을 모아 족보 시너지 발동",
		"震动反馈(轮到你/结算)": "진동 피드백(내 턴/결과)",
		"革命": "혁명",
		"音乐": "음악",
		"音效": "효과음",
		"音量": "음량",
		"领 取": "수  령",
		"，本回合有额外候选组!": ",이 라운드 추가 후보 있음!",
		"，额外候选组!": ",추가 후보 조합!",
		"🂡 大富豪": "🂡 대부호",
		"🎲  快速匹配": "🎲  빠른 대국",
		"🎲 肉鸽模式": "🎲 로그 모드",
		"🏠  创建房间": "🏠  방 만들기",
		"🏠 本机开房(当主机)": "🏠 로컬 호스트",
		"👁 观战中 — 本房间仅 1/2 号位可出战": "👁 관전 중 — 이 방은 1/2번석만 출전 가능",
		"💥 重击(防御可减!)": "💥 강타(방어로 경감!)",
		"📅 每日挑战": "📅 일일 챌린지",
		"📋 粘贴邀请码, 一键加入": "📋 초대 코드 붙여넣기",
		"📕 命运卡图鉴": "📕 운명 카드 도감",
		"🔍 搜索附近主机": "🔍 근처 호스트 검색",
		"🔥 法术(魔抗可减!)": "🔥 마법(마법 저항으로 경감!)",
		"🟣 奇物生效! 补抽一张普通牌": "🟣 유물 발동! 일반 카드 1장 추가 드로우",
		"🥊 联机格斗对战": "🥊 온라인 파이트 대전",
		"同一 WiFi 的朋友: 联机页点【搜索附近主机】一键加入\n异地朋友: 点【复制邀请码】发给他(含全部地址)": "같은 WiFi 친구: 온라인 페이지 [근처 호스트]로 원터치 참가\n원격 친구: [초대 코드 복사]를 보내세요(전체 주소 포함)",
		"Tailscale 已就绪 — 点【本机开房】创建房间, 把邀请码发给朋友;\n或点【粘贴邀请码, 一键加入】朋友的主机。": "Tailscale 준비 완료 — [로컬 호스트]로 방을 만들어 초대 코드를 공유;\n또는 [붙여넣기 참가]로 친구의 호스트에 접속。",
		"复活币生效!": "부활 코인 발동!",
		"第 1 回合 — %s 地下城": "라운드 1 — %s 던전",
		"奇物【%s】生效 — 补抽一张普通牌": "유물 [%s] 발동 — 일반 카드 1장 추가",
		"替换装备: 槽位 %d → %s": "장비 교체: 칸 %d → %s",
		"装备 %s(%d/5)": "장비 %s(%d/5)",
		"获得奇物【%s】%s": "유물 [%s] %s 획득",
		"第 %d 回合 %s: %s 出现! HP %d / 攻击 %d": "라운드 %d %s: %s 등장! HP %d / 공격 %d",
		"%s 被击破! 回复 %d 生命": "%s 격파! HP %d 회복",
		"第 %d 回合开始": "라운드 %d 시작",
		"BOSS 击破! 试炼通关!": "BOSS 격파! 시련 클리어!",
		"复活币发光 — 你重新站了起来!": "부활 코인이 빛난다 — 다시 일어섩니다!",
		"第 %d 回合 — 二选一编成": "라운드 %d — 택1 편성",
		"%s 获得奇物【%s】": "%s 유물 [%s] 획득",
		"%s 装备 %s(%d/5)": "%s 장비 %s(%d/5)",
		"对战开始 — %s 先攻": "전투 시작 — %s 선공",
		"%s 拿下第 %d 回合! (比分 %d:%d)": "%s 라운드 %d 획득! (%d:%d)",
		"★ %s 赢得整场格斗对战!": "★ %s 최종 승리!",
		"第 %d/%d 回合 · %s": "라운드 %d/%d · %s",
		"牌型 %s · %s": "족보 %s · %s",
		"装备后 %s": "장비 시 %s",
		"替换后 %s": "교체 시 %s",
		"🟣 奇物已生效 — 补抽一张普通牌 (装备 %d/5)": "🟣 유물 발동! 일반 카드 1장 추가 (장비 %d/5)",
		"第 %d 回合 — 二选一 (装备 %d/5)%s": "라운드 %d — 택1 (장비 %d/5)%s",
		"暴击 -%d": "치명타 -%d",
		"重击 -%d": "강타 -%d",
		"荆棘 -%d": "가시 -%d",
		"装备 %s": "장비 %s",
		"第 %d 回合 胜利!": "라운드 %d 승리!",
		"意图: %s": "의도: %s",
		"%s 冷却 %d": "%s 재사용 %d",
		"通过 %d/5 回合 · 历史最佳第 %d 层\n奖励: %d 钻石 已入账": "%d/5 라운드 통과 · 최고 %d\n보상: 다이아 %d 지급",
		"今日最佳: %s%s": "오늘 최고: %s%s",
		"通关! 剩余生命 %d%%": "클리어! 남은 HP %d%%",
		"到达第 %d 回合": "라운드 %d 도달",
		" (新纪录!)": " (신기록!)",
		"每日挑战通关!": "일일 클리어!",
		"每日挑战结束": "일일 종료",
		"第 %d 回合 — 对战!": "라운드 %d — 전투!",
		"第 %d 回合 结束": "라운드 %d 종료",
		"回合胜 %d": "라운드 승 %d",
		"装备 %d/5 · 奇物 %d": "장비 %d/5 · 유물 %d",
		"二选一 — 点选 1 张 (装备 %d/5%s)": "택1 — 1장 선택 (장비 %d/5%s)",
		"等待 %s 行动…": "%s 행동 대기…",
		"%s 拿下本回合 — 即将进入下一回合…": "%s 라운드 획득 — 다음 라운드로…",
		"比分 %d : %d — 胜者 %s": "스코어 %d : %d — 승자 %s",
		"奖励: %+d 金币 %+d 钻石 已入账": "보상: +%d 코인 +%d 다이아 지급",
		"场次 %d · 胜 %d · 胜率 %d%%": "경기 %d · 승 %d · 승률 %d%%",
		"场次 %d · 胜 %d": "경기 %d · 승 %d",
		"局数 %d · 通关 %d · 最远第 %d 回合 · 击破 BOSS %d": "판수 %d · 클리어 %d · 최고 라운드 %d · BOSS %d",
		"胜场 %d": "승 %d",
		"今日已通关(剩余生命 %d%%)": "오늘 클리어(남은 HP %d%%)",
		"今日最佳: 到达第 %d 回合": "오늘 최고: 라운드 %d",
		"累计参与 %d 天": "누적 %d일 참여",
		"已见 %d / %d 种": "확인 %d / %d종",
		"共 %d 场 · 胜 %d 场 · 胜率 %d%% · 称号 %s": "총 %d 판 · %d 승 · 승률 %d%% · 칭호 %s",
		"⚔ 格斗试炼最高纪录: 第 %d 回合": "⚔ 파이트 트라이얼 최고: 라운드 %d",
		"已解锁 %d / %d": "해금 %d / %d",
		"全设备同一天同一布局, 冲击今日最佳成绩": "모든 기기 같은 날 같은 배치, 오늘 최고 기록에 도전",
		"🔥 火球": "🔥화염구",
		"❄ 冰霜": "❄서리",
		"✟ 圣光": "✟성광",
		"⚡ 奥义": "⚡ 오의",
		"奥义 -%d": "오의 -%d",
		"完美格挡! 反击 -%d": "퍼펙트 가드! 반격 -%d",
		"稀有卡! 生命上限 +8%": "레어! 최대 HP +8%",
		"稀有!": "레어!",
		"COMBO x%d": "콤보 x%d",
		"人 物 皮 肤": "캐릭터 스킨",
		"卡 牌 面 貌": "카드 덱",
		"特 殊 道 具": "특수 아이템",
		"装 备": "장착",
		"购 买": "구매",
		"已拥有": "보유 중",
		"使用中": "사용 중",
		"购买成功, 已生效!": "구매 성공, 발동!",
		"购买成功, 已装备!": "구매 성공, 장착!",
		"余额不足, 先去赚一赚吧": "잔액 부족 — 먼저 벌어보세요",
		"生效中·今日": "오늘 발동 중",
		"勝利": "승리",
		"敗北": "패배",
		"⚡ 蓄力中 — 全力输出(承伤 +50%)!": "⚡ 차지 중 — 집중 공격(피해 +50%)!",
		"⚡ 敌人蓄力中…": "⚡적 차지 중…",
		"BOSS 狂暴!": "BOSS 광폭화!",
		"狂暴! 攻击大幅提升!": "광폭! 공격 대폭 상승!",
		"连击里程碑!": "콤보 마일스톤!",
		"BOSS 击破! 可继续无尽挑战!": "BOSS 격파! 엔드레스 도전 가능!",
		"深入无尽挑战, 怪物每轮更强, 奖励随层数增长": "엔드레스 도전 — 더 강한 몬스터, 더 큰 보상",
		"继续无尽挑战": "엔드레스 도전",
		"领奖结算": "보상 받기",
		"  评级 %s": "  등급 %s",
		"稀有卡! 生命上限永久 +8%": "레어! 최대 HP 영구 +8%",
		"切换后全界面即时生效": "전환 후 전체 UI에 즉시 적용",
	},
	"es": {
		"本地游戏": "Juego local",
		"联机游戏": "Juego online",
		"商　城": "TIENDA",
		"设  置": "AJUSTES",
		"设　置": "AJUSTES",
		"新手引导": "Tutorial",
		"退出游戏": "Salir",
		"选择游戏模式": "Elegir modo de juego",
		"AI 难度": "Dificultad IA",
		"简单": "Fácil",
		"普通": "Normal",
		"普通模式": "Modo clásico",
		"肉鸽模式": "Modo rogue",
		"格斗试炼": "Trial de lucha",
		"每日挑战": "Reto diario",
		"开始游戏": "Empezar partida",
		"返回菜单": "Volver al menú",
		"返回大厅": "Volver al vestíbulo",
		"返 回": "VOLVER",
		"取消": "Cancelar",
		"留在房间": "Quedarse",
		"连接": "Conectar",
		"加入": "Unirse",
		"房间": "Sala",
		"房主": "Anfitrión",
		"复制邀请码": "Copiar código",
		"等待加入": "Esperando",
		"观战中": "Espectando",
		"格斗者": "Luchador",
		"格斗对战": "Duelo de lucha",
		"装备槽": "Equipamiento",
		"音乐": "Música",
		"音效": "Efectos",
		"音量": "Volumen",
		"语言": "Idioma",
		"全屏": "Pantalla completa",
		"昵称": "Apodo",
		"保存并关闭": "Guardar y cerrar",
		"成  就": "LOGROS",
		"战  绩": "RÉCORDS",
		"每日任务": "Misiones",
		"统  计": "ESTADÍSTICAS",
		"已解锁": "Desbloqueado",
		"未解锁": "Bloqueado",
		"签 到 领 取": "RECLAMAR",
		"签到": "Registro diario",
		"玩家": "Jugador",
		"带王": "Con comodines",
		"革命": "Revolución",
		"输赢": "Apuesta",
		"回合数": "Rondas",
		"模式": "Modo",
		"规则设置": "Reglas",
		"⚔ 攻击": "⚔ Atacar",
		"🛡 防御": "🛡 Defender",
		"✨ 技能": "✨ Habilidad",
		"放弃试炼": "Abandonar",
		"胜 利 !": "¡VICTORIA!",
		"败 北…": "DERROTA…",
		"小怪": "Mobo",
		"精英怪": "Élite",
	},
	"fr": {
		"本地游戏": "Jeu local",
		"联机游戏": "Jeu en ligne",
		"商　城": "BOUTIQUE",
		"设  置": "RÉGLAGES",
		"设　置": "RÉGLAGES",
		"新手引导": "Tutoriel",
		"退出游戏": "Quitter",
		"选择游戏模式": "Choisir le mode",
		"AI 难度": "Difficulté IA",
		"简单": "Facile",
		"普通": "Normal",
		"普通模式": "Mode classique",
		"肉鸽模式": "Mode rogue",
		"格斗试炼": "Essai de combat",
		"每日挑战": "Défi quotidien",
		"开始游戏": "Commencer",
		"返回菜单": "Retour au menu",
		"返回大厅": "Retour au hall",
		"返 回": "RETOUR",
		"取消": "Annuler",
		"留在房间": "Rester",
		"连接": "Connexion",
		"加入": "Rejoindre",
		"房间": "Salle",
		"房主": "Hôte",
		"复制邀请码": "Copier le code",
		"等待加入": "En attente",
		"观战中": "Spectateur",
		"格斗者": "Combattant",
		"格斗对战": "Duel de combat",
		"装备槽": "Équipement",
		"音乐": "Musique",
		"音效": "Sons",
		"音量": "Volume",
		"语言": "Langue",
		"全屏": "Plein écran",
		"昵称": "Pseudo",
		"保存并关闭": "Enregistrer",
		"成  就": "SUCCÈS",
		"战  绩": "PALMARÈS",
		"每日任务": "Missions",
		"统  计": "STATS",
		"已解锁": "Débloqué",
		"未解锁": "Verrouillé",
		"签 到 领 取": "RÉCLAMER",
		"签到": "Connexion journal.",
		"玩家": "Joueur",
		"带王": "Avec jokers",
		"革命": "Révolution",
		"输赢": "Mise",
		"回合数": "Manches",
		"模式": "Mode",
		"规则设置": "Règles",
		"⚔ 攻击": "⚔ Attaquer",
		"🛡 防御": "🛡 Défendre",
		"✨ 技能": "✨ Compét.",
		"放弃试炼": "Abandonner",
		"胜 利 !": "VICTOIRE !",
		"败 北…": "DÉFAITE…",
		"小怪": "Mob",
		"精英怪": "Élite",
	},
	"de": {
		"本地游戏": "Lokal",
		"联机游戏": "Online",
		"商　城": "SHOP",
		"设  置": "OPTIONEN",
		"设　置": "OPTIONEN",
		"新手引导": "Tutorial",
		"退出游戏": "Beenden",
		"选择游戏模式": "Spielmodus wählen",
		"AI 难度": "KI-Stärke",
		"简单": "Leicht",
		"普通": "Normal",
		"普通模式": "Klassik-Modus",
		"肉鸽模式": "Rogue-Modus",
		"格斗试炼": "Kampf-Trial",
		"每日挑战": "Tageschallenge",
		"开始游戏": "Spiel starten",
		"返回菜单": "Zum Menü",
		"返回大厅": "Zur Lobby",
		"返 回": "ZURÜCK",
		"取消": "Abbrechen",
		"留在房间": "Bleiben",
		"连接": "Verbinden",
		"加入": "Beitreten",
		"房间": "Raum",
		"房主": "Host",
		"复制邀请码": "Code kopieren",
		"等待加入": "Wartend",
		"观战中": "Zuschauer",
		"格斗者": "Kämpfer",
		"格斗对战": "Kampf-Duell",
		"装备槽": "Ausrüstung",
		"音乐": "Musik",
		"音效": "Sound",
		"音量": "Lautstärke",
		"语言": "Sprache",
		"全屏": "Vollbild",
		"昵称": "Name",
		"保存并关闭": "Speichern",
		"成  就": "ERFOLGE",
		"战  绩": "STATISTIK",
		"每日任务": "Missionen",
		"统  计": "ÜBERSICHT",
		"已解锁": "Freigeschaltet",
		"未解锁": "Gesperrt",
		"签 到 领 取": "ABHOLEN",
		"签到": "Anmeldung",
		"玩家": "Spieler",
		"带王": "Mit Jokern",
		"革命": "Revolution",
		"输赢": "Einsatz",
		"回合数": "Runden",
		"模式": "Modus",
		"规则设置": "Regeln",
		"⚔ 攻击": "⚔ Angreifen",
		"🛡 防御": "🛡 Verteidigen",
		"✨ 技能": "✨ Skill",
		"放弃试炼": "Aufgeben",
		"胜 利 !": "SIEG !",
		"败 北…": "NIEDERLAGE…",
		"小怪": "Mob",
		"精英怪": "Elite",
	},
	"pt": {
		"本地游戏": "Jogo local",
		"联机游戏": "Jogo online",
		"商　城": "LOJA",
		"设  置": "AJUSTES",
		"设　置": "AJUSTES",
		"新手引导": "Tutorial",
		"退出游戏": "Sair",
		"选择游戏模式": "Escolher modo",
		"AI 难度": "Dificuldade IA",
		"简单": "Fácil",
		"普通": "Normal",
		"普通模式": "Modo clássico",
		"肉鸽模式": "Modo rogue",
		"格斗试炼": "Trial de luta",
		"每日挑战": "Desafio diário",
		"开始游戏": "Iniciar partida",
		"返回菜单": "Voltar ao menu",
		"返回大厅": "Voltar ao lobby",
		"返 回": "VOLTAR",
		"取消": "Cancelar",
		"留在房间": "Ficar",
		"连接": "Conectar",
		"加入": "Entrar",
		"房间": "Sala",
		"房主": "Anfitrião",
		"复制邀请码": "Copiar código",
		"等待加入": "Aguardando",
		"观战中": "Assistindo",
		"格斗者": "Lutador",
		"格斗对战": "Duelo de luta",
		"装备槽": "Equipamento",
		"音乐": "Música",
		"音效": "Efeitos",
		"音量": "Volume",
		"语言": "Idioma",
		"全屏": "Tela cheia",
		"昵称": "Apelido",
		"保存并关闭": "Salvar e fechar",
		"成  就": "CONQUISTAS",
		"战  绩": "HISTÓRICO",
		"每日任务": "Missões",
		"统  计": "ESTATÍSTICAS",
		"已解锁": "Desbloqueado",
		"未解锁": "Bloqueado",
		"签 到 领 取": "RESGATAR",
		"签到": "Check-in",
		"玩家": "Jogador",
		"带王": "Com curingas",
		"革命": "Revolução",
		"输赢": "Aposta",
		"回合数": "Rodadas",
		"模式": "Modo",
		"规则设置": "Regras",
		"⚔ 攻击": "⚔ Atacar",
		"🛡 防御": "🛡 Defender",
		"✨ 技能": "✨ Habilidade",
		"放弃试炼": "Desistir",
		"胜 利 !": "VITÓRIA !",
		"败 北…": "DERROTA…",
		"小怪": "Mob",
		"精英怪": "Elite",
	},
	"it": {
		"本地游戏": "Gioco locale",
		"联机游戏": "Gioco online",
		"商　城": "NEGOZIO",
		"设  置": "IMPOSTAZ.",
		"设　置": "IMPOSTAZ.",
		"新手引导": "Tutorial",
		"退出游戏": "Esci",
		"选择游戏模式": "Scegli modalità",
		"AI 难度": "Difficoltà IA",
		"简单": "Facile",
		"普通": "Normale",
		"普通模式": "Modalità classica",
		"肉鸽模式": "Modalità rogue",
		"格斗试炼": "Prova di lotta",
		"每日挑战": "Sfida giornaliera",
		"开始游戏": "Inizia",
		"返回菜单": "Al menu",
		"返回大厅": "Alla lobby",
		"返 回": "INDIETRO",
		"取消": "Annulla",
		"留在房间": "Rimani",
		"连接": "Connetti",
		"加入": "Unisciti",
		"房间": "Stanza",
		"房主": "Host",
		"复制邀请码": "Copia codice",
		"等待加入": "In attesa",
		"观战中": "Spettatore",
		"格斗者": "Combattente",
		"格斗对战": "Duello di lotta",
		"装备槽": "Equipaggiamento",
		"音乐": "Musica",
		"音效": "Audio",
		"音量": "Volume",
		"语言": "Lingua",
		"全屏": "Schermo intero",
		"昵称": "Soprannome",
		"保存并关闭": "Salva",
		"成  就": "OBIETTIVI",
		"战  绩": "STORICO",
		"每日任务": "Missioni",
		"统  计": "STATISTICHE",
		"已解锁": "Sbloccato",
		"未解锁": "Bloccato",
		"签 到 领 取": "RITIRA",
		"签到": "Registrazione",
		"玩家": "Giocatore",
		"带王": "Con jolly",
		"革命": "Rivoluzione",
		"输赢": "Puntata",
		"回合数": "Manche",
		"模式": "Modalità",
		"规则设置": "Regole",
		"⚔ 攻击": "⚔ Attacca",
		"🛡 防御": "🛡 Difendi",
		"✨ 技能": "✨ Abilità",
		"放弃试炼": "Arrenditi",
		"胜 利 !": "VITTORIA !",
		"败 北…": "SCONFITTA…",
		"小怪": "Mob",
		"精英怪": "Élite",
	},
	"ru": {
		"本地游戏": "Локальная игра",
		"联机游戏": "Онлайн-игра",
		"商　城": "МАГАЗИН",
		"设  置": "НАСТРОЙКИ",
		"设　置": "НАСТРОЙКИ",
		"新手引导": "Обучение",
		"退出游戏": "Выход",
		"选择游戏模式": "Выбор режима",
		"AI 难度": "Сложность ИИ",
		"简单": "Легко",
		"普通": "Обычно",
		"普通模式": "Классика",
		"肉鸽模式": "Рогалик",
		"格斗试炼": "Бойцовское испытание",
		"每日挑战": "Ежедневный вызов",
		"开始游戏": "Начать игру",
		"返回菜单": "В меню",
		"返回大厅": "В лобби",
		"返 回": "НАЗАД",
		"取消": "Отмена",
		"留在房间": "Остаться",
		"连接": "Подключиться",
		"加入": "Войти",
		"房间": "Комната",
		"房主": "Хост",
		"复制邀请码": "Копировать код",
		"等待加入": "Ожидание",
		"观战中": "Наблюдатель",
		"格斗者": "Боец",
		"格斗对战": "Бой 1 на 1",
		"装备槽": "Снаряжение",
		"音乐": "Музыка",
		"音效": "Звуки",
		"音量": "Громкость",
		"语言": "Язык",
		"全屏": "Полный экран",
		"昵称": "Ник",
		"保存并关闭": "Сохранить",
		"成  就": "ДОСТИЖЕНИЯ",
		"战  绩": "РЕКОРДЫ",
		"每日任务": "Задания",
		"统  计": "СТАТИСТИКА",
		"已解锁": "Открыто",
		"未解锁": "Закрыто",
		"签 到 领 取": "ЗАБРАТЬ",
		"签到": "Вход ежедневно",
		"玩家": "Игрок",
		"带王": "С джокерами",
		"革命": "Революция",
		"输赢": "Ставка",
		"回合数": "Раунды",
		"模式": "Режим",
		"规则设置": "Правила",
		"⚔ 攻击": "⚔ Атака",
		"🛡 防御": "🛡 Защита",
		"✨ 技能": "✨ Умение",
		"放弃试炼": "Сдаться",
		"胜 利 !": "ПОБЕДА !",
		"败 北…": "ПОРАЖЕНИЕ…",
		"小怪": "Моб",
		"精英怪": "Элита",
	},
	"ar": {
		"本地游戏": "لعبة محلية",
		"联机游戏": "لعبة عبر الإنترنت",
		"商　城": "المتجر",
		"设  置": "الإعدادات",
		"设　置": "الإعدادات",
		"新手引导": "التعليمات",
		"退出游戏": "خروج",
		"选择游戏模式": "اختر وضع اللعب",
		"AI 难度": "صعوبة الذكاء",
		"简单": "سهل",
		"普通": "عادي",
		"普通模式": "الوضع الكلاسيكي",
		"肉鸽模式": "وضع الروغ",
		"格斗试炼": "تجربة القتال",
		"每日挑战": "التحدي اليومي",
		"开始游戏": "ابدأ اللعبة",
		"返回菜单": "القائمة الرئيسية",
		"返回大厅": "إلى البهو",
		"返 回": "رجوع",
		"取消": "إلغاء",
		"留在房间": "البقاء",
		"连接": "اتصال",
		"加入": "انضمام",
		"房间": "غرفة",
		"房主": "المضيف",
		"复制邀请码": "نسخ رمز الدعوة",
		"等待加入": "بانتظار الانضمام",
		"观战中": "مشاهدة",
		"格斗者": "مقاتل",
		"格斗对战": "مبارزة قتالية",
		"装备槽": "المعدات",
		"音乐": "الموسيقى",
		"音效": "المؤثرات",
		"音量": "الصوت",
		"语言": "اللغة",
		"全屏": "ملء الشاشة",
		"昵称": "الاسم",
		"保存并关闭": "حفظ وإغلاق",
		"成  就": "الإنجازات",
		"战  绩": "السجلات",
		"每日任务": "المهام",
		"统  计": "الإحصاءات",
		"已解锁": "مفتوح",
		"未解锁": "مغلق",
		"签 到 领 取": "استلام",
		"签到": "تسجيل الحضور",
		"玩家": "لاعب",
		"带王": "مع الجوكر",
		"革命": "الثورة",
		"输赢": "الرهان",
		"回合数": "الجولات",
		"模式": "الوضع",
		"规则设置": "القواعد",
		"⚔ 攻击": "⚔ هجوم",
		"🛡 防御": "🛡 دفاع",
		"✨ 技能": "✨ مهارة",
		"放弃试炼": "استسلام",
		"胜 利 !": "انتصار !",
		"败 北…": "هزيمة…",
		"小怪": "وحش",
		"精英怪": "نخبة",
	},
	"th": {
		"本地游戏": "เกมท้องถิ่น",
		"联机游戏": "เกมออนไลน์",
		"商　城": "ร้านค้า",
		"设  置": "ตั้งค่า",
		"设　置": "ตั้งค่า",
		"新手引导": "สอนเล่น",
		"退出游戏": "ออกเกม",
		"选择游戏模式": "เลือกโหมดเกม",
		"AI 难度": "ระดับ AI",
		"简单": "ง่าย",
		"普通": "ปกติ",
		"普通模式": "โหมดคลาสสิก",
		"肉鸽模式": "โหมดโร้ก",
		"格斗试炼": "ดวลตัวต่อตัว",
		"每日挑战": "ภารกิจประจำวัน",
		"开始游戏": "เริ่มเกม",
		"返回菜单": "กลับเมนู",
		"返回大厅": "กลับล็อบบี้",
		"返 回": "กลับ",
		"取消": "ยกเลิก",
		"留在房间": "อยู่ต่อ",
		"连接": "เชื่อมต่อ",
		"加入": "เข้าร่วม",
		"房间": "ห้อง",
		"房主": "เจ้าของห้อง",
		"复制邀请码": "คัดลอกรหัส",
		"等待加入": "รอเข้าร่วม",
		"观战中": "กำลังดู",
		"格斗者": "นักสู้",
		"格斗对战": "ต่อสู้ 1v1",
		"装备槽": "ช่องอุปกรณ์",
		"音乐": "เพลง",
		"音效": "เสียง",
		"音量": "ระดับเสียง",
		"语言": "ภาษา",
		"全屏": "เต็มจอ",
		"昵称": "ชื่อเล่น",
		"保存并关闭": "บันทึกและปิด",
		"成  就": "ความสำเร็จ",
		"战  绩": "สถิติ",
		"每日任务": "ภารกิจรายวัน",
		"统  计": "สถิติรวม",
		"已解锁": "ปลดล็อก",
		"未解锁": "ล็อก",
		"签 到 领 取": "รับรางวัล",
		"签到": "เช็คอิน",
		"玩家": "ผู้เล่น",
		"带王": "มีโจ๊กเกอร์",
		"革命": "ปฏิวัติ",
		"输赢": "เดิมพัน",
		"回合数": "รอบ",
		"模式": "โหมด",
		"规则设置": "กติกา",
		"⚔ 攻击": "⚔ โจมตี",
		"🛡 防御": "🛡 ป้องกัน",
		"✨ 技能": "✨ สกิล",
		"放弃试炼": "ยอมแพ้",
		"胜 利 !": "ชนะ !",
		"败 北…": "แพ้…",
		"小怪": "มอนสเตอร์",
		"精英怪": "เอลิท",
	},
	"vi": {
		"本地游戏": "Chơi local",
		"联机游戏": "Chơi online",
		"商　城": "CỬA HÀNG",
		"设  置": "CÀI ĐẶT",
		"设　置": "CÀI ĐẶT",
		"新手引导": "Hướng dẫn",
		"退出游戏": "Thoát game",
		"选择游戏模式": "Chọn chế độ",
		"AI 难度": "Độ khó AI",
		"简单": "Dễ",
		"普通": "Thường",
		"普通模式": "Chế độ cổ điển",
		"肉鸽模式": "Chế độ rogue",
		"格斗试炼": "Thử đấu võ",
		"每日挑战": "Thử thách ngày",
		"开始游戏": "Bắt đầu",
		"返回菜单": "Về menu",
		"返回大厅": "Về sảnh",
		"返 回": "TRỞ LẠI",
		"取消": "Hủy",
		"留在房间": "Ở lại",
		"连接": "Kết nối",
		"加入": "Tham gia",
		"房间": "Phòng",
		"房主": "Chủ phòng",
		"复制邀请码": "Sao chép mã",
		"等待加入": "Đang chờ",
		"观战中": "Đang xem",
		"格斗者": "Đấu sĩ",
		"格斗对战": "Đấu 1v1",
		"装备槽": "Trang bị",
		"音乐": "Nhạc",
		"音效": "Hiệu ứng",
		"音量": "Âm lượng",
		"语言": "Ngôn ngữ",
		"全屏": "Toàn màn hình",
		"昵称": "Biệt danh",
		"保存并关闭": "Lưu và đóng",
		"成  就": "THÀNH TỰU",
		"战  绩": "THÀNH TÍCH",
		"每日任务": "Nhiệm vụ",
		"统  计": "THỐNG KÊ",
		"已解锁": "Đã mở",
		"未解锁": "Đã khóa",
		"签 到 领 取": "NHẬN",
		"签到": "Điểm danh",
		"玩家": "Người chơi",
		"带王": "Có Joker",
		"革命": "Cách mạng",
		"输赢": "Cược",
		"回合数": "Số ván",
		"模式": "Chế độ",
		"规则设置": "Luật",
		"⚔ 攻击": "⚔ Tấn công",
		"🛡 防御": "🛡 Phòng thủ",
		"✨ 技能": "✨ Kỹ năng",
		"放弃试炼": "Bỏ cuộc",
		"胜 利 !": "CHIẾN THẮNG !",
		"败 北…": "THẤT BẠI…",
		"小怪": "Quái thường",
		"精英怪": "Quái tinh anh",
	},
	"id": {
		"本地游戏": "Main lokal",
		"联机游戏": "Main online",
		"商　城": "TOKO",
		"设  置": "PENGATURAN",
		"设　置": "PENGATURAN",
		"新手引导": "Tutorial",
		"退出游戏": "Keluar",
		"选择游戏模式": "Pilih mode",
		"AI 难度": "Tingkat AI",
		"简单": "Mudah",
		"普通": "Normal",
		"普通模式": "Mode klasik",
		"肉鸽模式": "Mode rogue",
		"格斗试炼": "Tarung ujian",
		"每日挑战": "Tantangan harian",
		"开始游戏": "Mulai",
		"返回菜单": "Ke menu",
		"返回大厅": "Ke lobi",
		"返 回": "KEMBALI",
		"取消": "Batal",
		"留在房间": "Tetap di ruang",
		"连接": "Sambung",
		"加入": "Gabung",
		"房间": "Ruang",
		"房主": "Tuan rumah",
		"复制邀请码": "Salin kode",
		"等待加入": "Menunggu",
		"观战中": "Menonton",
		"格斗者": "Petarung",
		"格斗对战": "Duel tarung",
		"装备槽": "Peralatan",
		"音乐": "Musik",
		"音效": "Efek suara",
		"音量": "Volume",
		"语言": "Bahasa",
		"全屏": "Layar penuh",
		"昵称": "Nama",
		"保存并关闭": "Simpan & tutup",
		"成  就": "PENCAPAIAN",
		"战  绩": "REKOR",
		"每日任务": "Misi harian",
		"统  计": "STATISTIK",
		"已解锁": "Terbuka",
		"未解锁": "Terkunci",
		"签 到 领 取": "KLAIM",
		"签到": "Absen",
		"玩家": "Pemain",
		"带王": "Dengan Joker",
		"革命": "Revolusi",
		"输赢": "Taruhan",
		"回合数": "Ronde",
		"模式": "Mode",
		"规则设置": "Aturan",
		"⚔ 攻击": "⚔ Serang",
		"🛡 防御": "🛡 Bertahan",
		"✨ 技能": "✨ Skill",
		"放弃试炼": "Menyerah",
		"胜 利 !": "MENANG !",
		"败 北…": "KALAH…",
		"小怪": "Mob",
		"精英怪": "Elite",
	},
	"tr": {
		"本地游戏": "Yerel oyun",
		"联机游戏": "Çevrimiçi",
		"商　城": "MAĞAZA",
		"设  置": "AYARLAR",
		"设　置": "AYARLAR",
		"新手引导": "Öğretici",
		"退出游戏": "Çıkış",
		"选择游戏模式": "Mod seç",
		"AI 难度": "AI zorluğu",
		"简单": "Kolay",
		"普通": "Normal",
		"普通模式": "Klasik mod",
		"肉鸽模式": "Rogue modu",
		"格斗试炼": "Dövüş denemesi",
		"每日挑战": "Günlük meydan okuma",
		"开始游戏": "Oyunu başlat",
		"返回菜单": "Menüye dön",
		"返回大厅": "Lobiye dön",
		"返 回": "GERİ",
		"取消": "İptal",
		"留在房间": "Kal",
		"连接": "Bağlan",
		"加入": "Katıl",
		"房间": "Oda",
		"房主": "Ev sahibi",
		"复制邀请码": "Kodu kopyala",
		"等待加入": "Bekliyor",
		"观战中": "İzleyici",
		"格斗者": "Savaşçı",
		"格斗对战": "Dövüş düellosu",
		"装备槽": "Ekipman",
		"音乐": "Müzik",
		"音效": "Ses efekt.",
		"音量": "Ses",
		"语言": "Dil",
		"全屏": "Tam ekran",
		"昵称": "Takma ad",
		"保存并关闭": "Kaydet & kapat",
		"成  就": "BAŞARIM",
		"战  绩": "KAYITLAR",
		"每日任务": "Görevler",
		"统  计": "İSTATİSTİK",
		"已解锁": "Açık",
		"未解锁": "Kapalı",
		"签 到 领 取": "AL",
		"签到": "Giriş",
		"玩家": "Oyuncu",
		"带王": "Jokerli",
		"革命": "Devrim",
		"输赢": "Bahis",
		"回合数": "Tur",
		"模式": "Mod",
		"规则设置": "Kurallar",
		"⚔ 攻击": "⚔ Saldır",
		"🛡 防御": "🛡 Savun",
		"✨ 技能": "✨ Yetenek",
		"放弃试炼": "Pes et",
		"胜 利 !": "ZAFER !",
		"败 北…": "YENİLGİ…",
		"小怪": "Canavar",
		"精英怪": "Elit",
	},
}
